### ISSUE TITLE
Exporting with baked animation fails with non-standard curve types.  

### ISSUE THREAD

**Issue by spiraloid** [KhronosGroup/glTF-Blender-IO#1027]
**Describe the bug**
If you animate using special keyframe interpolation (like bounce, quarctic, etc) using the "t" menu on keyframes and then try to export a .gltf file, it doesn't matter if you have "Animation" +  "Always Sample Animations" properties true or not.     If you have non-default key interpolation types on any keyframes, you will get an error complaining about the unknown interpolation type.  

The user shouldn't have to go manually select all the objects with a special key interpolation on them and choose "object > animation > bake action" before exporting.  It should be automatic.  that's why the "always sample animations" checkbox exists no?

This is a bug since when you export with "Always Sample Animations" active, any key interpolation type becomes is irrelevant since all the animation is supposed to get sampled (baked) per frame regardless.   

**To Reproduce**
create a camera.
set some keyframes.
select all keyframes in the dope sheet and hit "t" choose quartic as the key interpolation type.
export a .gltf file with "Selected Objects" false,  "Animation" true, "Always Sample Animations" true.

see error below.

**Expected behavior**
I expect it to bake the animation for all keys, set the interpolation type to linear and save the .glb file without erroring.

**Screenshots**

**Version**
 - OS: windows
 - Blender Version 2.82a and 2.83

y'all are awesome.

**Comment by spiraloid** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\__init__.py", line 481, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 53, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 62, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 39, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 73, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(blender_object, merged_tracks, len(animations), export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 68, in gather_animations
    animation = __gather_animation(blender_action, blender_object, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 103, in __gather_animation
    channels=__gather_channels(blender_action, blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 139, in __gather_channels
    blender_action, blender_object, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 119, in gather_animation_channels
    channel = __gather_animation_channel(channel_group_sorted, blender_object, export_settings, None, None, bake_range_start, bake_range_end, blender_action.name, None)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 193, in __gather_animation_channel
    sampler=__gather_sampler(channels, blender_object, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, action_name, driver_obj),
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 253, in __gather_sampler
    export_settings
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 66, in gather_animation_sampler
    interpolation=__gather_interpolation(channels, blender_object_if_armature, export_settings, bake_bone, bake_channel),
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 282, in __gather_interpolation
    }[blender_keyframe.interpolation]
KeyError: 'QUART'

location: <unknown location>:-1

**Comment by julienduroure** [comment]
Fixed by f5dad16
