### ISSUE TITLE
Object can't be exported as .glb if it has a parent

### ISSUE THREAD

**Issue by Moonwards** [KhronosGroup/glTF-Blender-IO#1030]
**Describe the bug**
An object with a parent will export as an empty file. If the file created is imported into a blender file (2.81a), the following errors are generated:

bpy.context.space_data.system_bookmarks_active = 1
Traceback (most recent call last):
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 923, in execute
    return self.import_gltf2(context)
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 937, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 960, in unit_import
    BlenderGlTF.create(self.gltf_importer)
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 30, in create
    BlenderScene.create(gltf)
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 60, in create
    BlenderScene.set_active_object(gltf)
  File "/home/kim/3dDev/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 88, in set_active_object
    vnode = gltf.vnodes[pyscene.nodes[0]]
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1

bpy.context.area.ui_type = 'INFO'

**To Reproduce**
1. Open new file, duplicate the cube
2. Parent one cube to the other
3. Export the child cube as a .glb, selecting the option `Include: Selected Objects`
4. Attempt to import the .glb in a blender file

**Expected behavior**
I would have thought that this parameter would be discarded and the object(s) exported as though they had no parent

This is so easy to reproduce I'll leave it as an exercise for the viewer 

**Version**
 - OS: Ubuntu 18.04
 - Blender Version 2.81a, 2.82a

**Additional context**
In 2.82a, the error is silent, the file simply doesn't import anything.

**Comment by scurest** [comment]
Cf #193

**Comment by emackey** [comment]
Fixed in #1126.
