### ISSUE TITLE
T76161: import error (exported from Google Tilt Brush)

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1045]
See https://developer.blender.org/T76161
File: https://drive.google.com/open?id=1Iu6Tda_nrmE1u3RBVtkOlopHSbR-o_gL

>Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/__init__.py", line 850, in execute
    return self.import_gltf2(context)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/__init__.py", line 864, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/__init__.py", line 887, in unit_import
    BlenderGlTF.create(self.gltf_importer)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 41, in create
    BlenderScene.create(gltf, scene_idx)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 80, in create
    BlenderNode.create(gltf, node_idx, None)  # None => No parent
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 174, in create
    BlenderNode.create(gltf, child_idx, node_idx)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 64, in create
    mesh = BlenderMesh.create(gltf, pynode.mesh, node_idx, parent)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 57, in create
    BlenderMaterial.create(gltf, prim.material, vertex_color)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py", line 98, in create
    BlenderNormalMap.create(gltf, material_idx, vertex_color)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_map_normal.py", line 29, in create
    BlenderNormalMap.create_nodetree(gltf, material_idx, vertex_color)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_map_normal.py", line 42, in create_nodetree
    if len([node for node in node_tree.nodes if node.type == "BSDF_PRINCIPLED"]) != 0:
AttributeError: 'NoneType' object has no attribute 'nodes'
>
>location: <unknown location>:-1

**Comment by scurest** [comment]
Test file is enormous. The trace contains stuff that's been deleted since 2.82 though. Does it happen on master?

**Comment by julienduroure** [comment]
My anwser on d.b.o :
>Hello,
Can you please test on a recent builds, for example 2.83beta and 2.90alpha. We can download them here : https://builder.blender.org/download/
(Asking because some part of traceback are no more on current code)
Can you please provide a *simple* test file. Providing a simplier file will help us to understand what the real problem is, and will save our time (if the problem still occurs on recent builds)
Thanks!

**Comment by julienduroure** [comment]
Fix is confirmed by user on recent build. Closing
