### ISSUE TITLE
GBL export AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

### ISSUE THREAD

**Issue by therset** [KhronosGroup/glTF-Blender-IO#1060]
Hello, 
first thanks for this exporter is been working fab.
I have been getting this error after many successful export :( I am at a loss

**To Reproduce**
1. Go to 'exporter'
2. Click on 'I have remember settings clicked so nothing changed on exporter'
3.Click export
4. See error as follows and after I have duplicated geometries..:

AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/__init__.py", line 502, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 42, in save
    json, buffer = __export(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 55, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 64, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 60, in __gather_scene
    blender_scene, None, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, library, blender_scene, dupli_object_parent, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 65, in __gather_node
    mesh=__gather_mesh(blender_object, library, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 333, in __gather_mesh
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 44, in gather_mesh
    primitives=__gather_primitives(blender_mesh, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 136, in __gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 62, in gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 56, in gather_material
    pbr_metallic_roughness=__gather_pbr_metallic_roughness(blender_material, orm_texture, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 219, in __gather_pbr_metallic_roughness
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 37, in gather_material_pbr_metallic_roughness
    metallic_roughness_texture=__gather_metallic_roughness_texture(blender_material, orm_texture, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 158, in __gather_metallic_roughness_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(texture_input, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 37, in gather_texture_info
    index=__gather_index(blender_shader_sockets_or_texture_slots, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 97, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 48, in gather_texture
    source=__gather_source(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 97, in __gather_source
    return gltf2_blender_gather_image.gather_image(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 49, in gather_image
    buffer_view = __gather_buffer_view(image_data, mime_type, name, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 86, in __gather_buffer_view
    return gltf2_io_binary_data.BinaryData(data=image_data.encode(mime_type))
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 118, in encode
    return self.__encode_unhappy()
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 147, in __encode_unhappy
    image.pixels.foreach_get(tmp_buf)
AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

location: <unknown location>:-1

**Expected behavior**
Export GBL as has been doing before, inc animation, uv etc.

**Screenshots**
![Screenshot 2020-05-07 at 11 43 45](https://user-images.githubusercontent.com/34192263/81285870-13af5180-9058-11ea-81c0-248270e5704c.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: Mac
 - Blender Version 2.82

**Comment by therset** [comment]
Blender File
[masterd.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4592467/masterd.blend.zip)

**Comment by scurest** [comment]
How did you install the addon? The addon version you're using needs a higher version of Blender than 2.82.

**Comment by therset** [comment]
hello, add-on is on default, I figure it out anyway but thanks sooo much,
it seems the error is given when you have textures on the node for
attributes that won't export directly, e.g. needs baking and so on.

Will be nice to have a way to export all maps without baking
:)

>

**Comment by scurest** [comment]
The foreach_get method was added in 2.83

> * New foreach_set and foreach_get methods on array properties like image pixels. This is significantly more efficient than accessing individual elements.
> 
> https://wiki.blender.org/wiki/Reference/Release_Notes/2.83/Python_API

It started to be used in #1018, which also bumped the addon's required Blender version to 2.83.9 (9d121bda55).

So this issue is only possible if you use the 2.83 version of the addon in 2.82.

2.83 is now the stable version of Blender anyway.

So can this be closed?

**Comment by julienduroure** [comment]
Closing. Don't hesitate to comment and/or reopen if we missed something or if you still have an issue, using default factory blender.
