### ISSUE TITLE
Gltf import fails in add_primitives_to_bmesh

### ISSUE THREAD

**Issue by Setyadjih** [KhronosGroup/glTF-Blender-IO#1108]
**Describe the bug**
Importing certain gltf files results in an IndexError during import, resulting in only part of the mesh being imported. The info panel gives this error traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 900, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 914, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 937, in unit_import
    BlenderGlTF.create(self.gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 42, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 49, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 40, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 38, in create_vnode
    BlenderNode.create_object(gltf, vnode_id)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 58, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 207, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 64, in create
    BlenderPrimitive.add_primitive_to_bmesh(gltf, bme, pymesh, prim, skin_idx, material_idx)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_primitive.py", line 228, in add_primitive_to_bmesh
    u, v = uvs[pidx]
IndexError: list index out of range

location: <unknown location>:-1
```

The file appears normally through BabylonJS or the windows Mixed Reality Viewer

**To Reproduce**
1. Download the attached zip file
2. Extract the archive into a folder
3. Import the .gltf file into blender

**Expected behavior**
Gltf file should import into scene

**Screenshots**
Import error:
![image](https://user-images.githubusercontent.com/9144286/86099155-b250af80-bae9-11ea-867d-6439e3d15173.png)

BabylonJs:
![image](https://user-images.githubusercontent.com/9144286/86099363-f8a60e80-bae9-11ea-88db-9ca6da1fcd5f.png)

Mixed Reality Viewer:
![image](https://user-images.githubusercontent.com/9144286/86099388-0065b300-baea-11ea-9777-3f696130b7e6.png)

**.blend file/ .gltf**
The file is larger than 10Mb, so I'll place a link to download:
https://drive.google.com/file/d/1sxl7u7YpsyV9ZxJ3g0FjnI2C4t31do62/view?usp=sharing

**Version**
 - OS: Win10
 - Blender Version 2.83.0

**Comment by scurest** [comment]
The indices in your file do appear to be out of bounds. Can you confirm that's correct?

The first error occurs on the mesh MatShape_98500.

```
cleaned-shirt $ jq .meshes[4] cleaned-shirt.gltf 
{
  "name": "MatShape_98500",
  "primitives": [
    {
      "attributes": {
        "NORMAL": 18,
        "POSITION": 17,
        "TEXCOORD_0": 19
      },
      "indices": 16,
      "material": 1
    }
  ]
}
```

The POSITION accessor has count=64, while the TEXCOORD_0 accessor has count=32

```
cleaned-shirt $ jq .accessors[17].count cleaned-shirt.gltf 
64
cleaned-shirt $ jq .accessors[19].count cleaned-shirt.gltf 
32
```

And the indices accessor decodes to `(0, 1, 2, ..., 57, 61, 62)`, so some of the indices are indeed OOB for TEXCOORD_0.

**Comment by Setyadjih** [comment]
Thanks for the rapid response, I'll double check the file source. and see what adjustments can be made.

Are there any suggested workarounds in this situation in the meantime? I'm curious as to why they might be loading in other gltf viewers but not Blender.

**Comment by scurest** [comment]
I believe the viewers are just reading the data from the buffer view outside the range of the accessor.

Here's a quick and dirty patch for the addon that appears to make the import go through

<details>

<summary>Patch</summary>

````diff
diff --git a/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py b/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
index d544778..83dbdad 100755
--- a/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
+++ b/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py
@@ -42,6 +42,10 @@ class BlenderPrimitive():
             pyprimitive.num_faces = 0
             return
 
+        pos_count = gltf.data.accessors[attributes['POSITION']].count
+        for acc_idx in attributes.values():
+            gltf.data.accessors[acc_idx].count = pos_count
+
         positions = BinaryData.get_data_from_accessor(gltf, attributes['POSITION'], cache=True)
 
         if pyprimitive.indices is not None:
diff --git a/addons/io_scene_gltf2/io/imp/gltf2_io_binary.py b/addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
index 7cfcbc4..9f96b0b 100644
--- a/addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
+++ b/addons/io_scene_gltf2/io/imp/gltf2_io_binary.py
@@ -55,7 +55,7 @@ class BinaryData():
         if byte_offset is None:
             byte_offset = 0
 
-        return buffer[byte_offset:byte_offset + buffer_view.byte_length]
+        return buffer[byte_offset:]
 
     @staticmethod
     def get_data_from_accessor(gltf, accessor_idx, cache=False):
````

</details>

![shirt](https://user-images.githubusercontent.com/11024420/86114840-bac8cc00-ba90-11ea-8292-ce93f55433ef.png)

**Comment by Setyadjih** [comment]
Just tried out the patch, seems to be working great! Thanks @scurest. I'll run more extensive tests along this week and let you know if there's anything that goes oddly.

Any chance of this patch going into the official addon?

**Comment by scurest** [comment]
No, it was just a hack to make this one file work. The program that made this glTF needs to be fixed. glTF validator also has other problems with this file (eg. not listing byteStrides).

**Comment by Setyadjih** [comment]
Alright, understood. I'll pass along all the relevant information. Thanks again for the help!
