### ISSUE TITLE
Export crashes in 2.79

### ISSUE THREAD

**Issue by UX3D-schmithuesen** [KhronosGroup/glTF-Blender-IO#115]
The [model](https://github.com/KhronosGroup/glTF-Blender-IO/files/2556025/menorah-example.zip) taken from #65 exports (more or less) fine in `Blender 2.80`, but exits with the following error in `Blender 2.79`:
```
INFO: Starting glTF 2.0 export
Traceback (most recent call last):
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\__init__.py", line 392, in execute
    return gltf2_blender_export.save(self, context, export_settings)
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 38, in save
    scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 32, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 49, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, export_settings)
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 31, in gather_node
    if not __filter_node(blender_object, export_settings):
  File "C:\Users\Ben\glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 64, in __filter_node
    if blender_object.instance_collection is not None and not blender_object.instance_collection.layers[0]:
AttributeError: 'Object' object has no attribute 'instance_collection'
```

**Comment by julienduroure** [comment]
I can confirm.
I forgot to implement retro compatibility during last merge from blender
repo.

I will take care on that ASAP

**Comment by julienduroure** [comment]
Here is problematic commit : 84c97fd01ae1c76897f1a0d95a97638a061d3295
Need to add a check on version

**Comment by julienduroure** [comment]
Should be back to normal for 2.79 now
