### ISSUE TITLE
Blender 2.8 Export GLTF error messages

### ISSUE THREAD

**Issue by enzyme69** [KhronosGroup/glTF-Blender-IO#116]
I am testing Blender 2.8 Beta, it seems to have GLB and GLTF exporter.

Scene is simple, just Principles with some PBR textures: albedo, metalness, etc.
<img width="648" alt="screen shot 2018-11-30 at 11 04 17 pm" src="https://user-images.githubusercontent.com/3952687/49288256-62b49700-f4f4-11e8-87f3-da32951bde1e.png">

Getting this error:
```
Traceback (most recent call last):
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 380, in execute
    return gltf2_blender_export.save(self, context, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 38, in save
    scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 32, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 49, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 40, in gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 137, in __gather_mesh
    return gltf2_blender_gather_mesh.gather_mesh(blender_object.data, vertex_groups, modifiers, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 35, in gather_mesh
    primitives=__gather_primitives(blender_mesh, vertex_groups, modifiers, export_settings),
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 81, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh, vertex_groups, modifiers, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 55, in gather_primitives
    material=__gather_materials(internal_primitive, blender_mesh, modifiers, export_settings),
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 69, in __gather_materials
    return gltf2_blender_gather_materials.gather_material(material, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 50, in gather_material
    pbr_metallic_roughness=__gather_pbr_metallic_roughness(blender_material, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 137, in __gather_pbr_metallic_roughness
    export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 34, in gather_material_pbr_metallic_roughness
    metallic_roughness_texture=__gather_metallic_roughness_texture(blender_material, export_settings),
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 85, in __gather_metallic_roughness_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(texture_input, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 33, in gather_texture_info
    index=__gather_index(blender_shader_sockets_or_texture_slots, export_settings),
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 62, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 47, in gather_texture
    source=__gather_source(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 88, in __gather_source
    return gltf2_blender_gather_image.gather_image(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 39, in gather_image
    uri=__gather_uri(blender_shader_sockets_or_texture_slots, export_settings)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 85, in __gather_uri
    return __get_image_data(sockets_or_slots)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 137, in __get_image_data
    image.add_to_image(image_data)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181129.26d5a3625ed-x86_64/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_image_data.py", line 38, in add_to_image
    raise ValueError("Can't append image: channels full")
ValueError: Can't append image: channels full

location: <unknown location>:-1


```

I am wondering if I am doing it correctly? Is there documentation?

**Comment by enzyme69** [comment]
[monkey_PBR_005.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2633121/monkey_PBR_005.blend.zip)

Here is the Blend file to play with. Please use Blender 2.8 Beta.

**Comment by enzyme69** [comment]
I tested with material only with Albedo and Normal, seems like not getting error. But if I am also adding textures for both Metalness and Roughness, it gives the error.

Is it still the norm that Metalness and Roughness is coming from a single material and it automatically takes the R and G?

**Comment by enzyme69** [comment]
After investigation so far: 
- only Albedo and Normal texture correctly exported with GLTF.
- Metalness or Roughness are not exported
- "Apply Modifier" is not being respected

**Comment by enzyme69** [comment]
And... also curious on where to plug Occlusion map in Principled? Hmm... 🤔

**Comment by dsinni** [comment]
@enzyme69 
> Is it still the norm that Metalness and Roughness is coming from a single material and it automatically takes the R and G?

From what I understand from https://www.khronos.org/blog/art-pipeline-for-gltf, `RGB` translates to `ORM`, so:

R = Ambient Occlusion
G = Roughness
B = Metallic

At least, I think it's _supposed_ to work that way; I've also been having issues getting this to work in the Blender/Exporter Beta.

I'm also not sure if it's supposed to be automatic or if you need to run it through the `Separate RGB` node, but I've been seeing some node configuration demos using the latter.
