### ISSUE TITLE
bpy.ops.import_scene.gltf doesn't work with bpy.ops.wm.read_factory_settings?

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1183]
I'm trying to load gltf after clearing the scene, like shown here:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/7a3532e32fcce61ab08aa0c081282e72e668ea4c/tests/roundtrip_gltf.py
But I'm getting the error:

```
Error: Traceback (most recent call last):
  File "\Text", line 34, in <module>
  File "\Text", line 32, in process_one
  File "\Text", line 12, in process_gltf
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 900, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 919, in import_gltf2
    return self.unit_import(self.filepath, import_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\__init__.py", line 937, in unit_import
    BlenderGlTF.create(self.gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 42, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 49, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 40, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 40, in create_vnode
    BlenderNode.create_bones(gltf, vnode_id)
  File "C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 134, in create_bones
    bpy.context.window.scene = bpy.data.scenes[gltf.blender_scene]
AttributeError: 'NoneType' object has no attribute 'scene'

location: C:\Program Files\Blender Foundation\Blender 2.83.4\2.83\scripts\modules\bpy\ops.py:201
```

**Comment by scurest** [comment]
Does it work if you delete that line?

**Comment by emackey** [comment]
I ran into this too.  The factory reset is being used to get rid of Blender's default cube, light, and camera, prior to a round-trip test.  But in recent versions of Blender, the factory reset actually resets the system scripts folder, killing off the developer's custom build of the glTF addon itself.

**Comment by emackey** [comment]
Actually mine had a different stack trace, not sure if it's the same as this.  But the factory reset got more aggressive at some point along the 2.8x series of releases, and caused problems for me.

**Comment by scurest** [comment]
Okay, I can reproduce OP's stack trace. To trigger it you need to run blender _without_ the `-b` (headless) option. Deleting that line does not fix it, it will error again when we try to switch to edit mode.

I'm assuming this is for the same reason as: https://stackoverflow.com/questions/28075599/opening-blend-files-using-blenders-python-api/28083541#28083541

#1184 does fix it.
