### ISSUE TITLE
AssertionError on gltf import to blender

### ISSUE THREAD

**Issue by rix911** [KhronosGroup/glTF-Blender-IO#1199]
**Describe the bug**
Traceback (most recent call last):
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 928, in execute
    return self.import_gltf2(context)
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 942, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 955, in unit_import
    success, txt = self.gltf_importer.read()
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\io\imp\gltf2_io_gltf.py", line 164, in read
    self.data = gltf_from_dict(json.loads(content, parse_constant=glTFImporter.bad_json_value))
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1218, in gltf_from_dict
    return Gltf.from_dict(s)
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1181, in from_dict
    textures = from_union([lambda x: from_list(Texture.from_dict, x), from_none], obj.get("textures"))
  File "F:\Blender\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1

**To Reproduce**
1. Go to blender and select import -> gltf 
2. See error

**Version**
 - OS: Win10
 - Blender Version 2.90.0

**Comment by scurest** [comment]
You didn't upload the file. You would normally see that error on an invalid file though.

**Comment by julienduroure** [comment]
Hello,
1 month without any answer. Closing this ticket. 
Don't hesitate to reopen and comment if you add the gltf file in attachment
