### ISSUE TITLE
Blend animation cannot be exported

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#1307]
**Describe the bug**
I have a test model that appears to be a valid blend file but cannot be exported to gltf.

**To Reproduce**
1. Open the Blend file.
2. Click on export glb.

```
Python: Traceback (most recent call last):
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\__init__.py", line 559, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 110, in __fix_json
    fixed[key] = __fix_json(value)
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 114, in __fix_json
    fixed.append(__fix_json(value))
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 110, in __fix_json
    fixed[key] = __fix_json(value)
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 114, in __fix_json
    fixed.append(__fix_json(value))
  File "C:\Users\ernest.lee\scoop\apps\blender\current\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 117, in __fix_json
    if int(obj) == obj:
ValueError: cannot convert float NaN to integer

location: <unknown location>:-1
```

**Expected behavior**
Not fail.

**Screenshots**

**.blend file/ .gltf**

[assimp-mdb-sphere_rig_advanced.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5773172/assimp-mdb-sphere_rig_advanced.zip)

**Version**
 - OS: win 10 
 - Blender Version 2.91.0

**Additional context**
https://github.com/assimp/assimp-mdb/tree/master/model-db/fbx/sphere_rig_advanced

**Comment by scurest** [comment]
The .blend is very strange. The NaN ultimately comes from the `bone.matrix_local` of three bones, namely

````
DW_SP1_Offset
<Matrix 4x4 (nan, nan, nan, -0.0000)
            (nan, nan, nan, -0.0000)
            (nan, nan, nan,  1.7401)
            (nan, nan, nan,  1.0000)>

Jnt_Ctrl_L_Down_Root_Offset_GRP
<Matrix 4x4 (-nan, -nan, -nan, nan)
            (-nan, -nan, -nan, nan)
            (-nan, -nan, -nan, nan)
            (-nan, -nan, -nan, nan)>

Jnt_Ctrl_L_Down_Root_Offset
<Matrix 4x4 (nan, nan, nan, nan)
            (nan, nan, nan, nan)
            (nan, nan, nan, nan)
            (nan, nan, nan, nan)>
````

I do not know how the .blend could have gotten into this state, but if you select the arma and toggle in and out of edit mode (which recalculates the matrix_locals), this is fixed and the model exports fine.

Also note that exporting to .dae produces a file with a bunch of NaNs in it.

**Comment by fire** [comment]
Who’s responsible to do the recalculate matrix locals?

**Comment by scurest** [comment]
Blender does it whenever you exit edit mode I believe. It's a [read-only property](https://docs.blender.org/api/current/bpy.types.Bone.html#bpy.types.Bone.matrix_local). How did you make the .blend file?

**Comment by fire** [comment]
1. I tried importing using the regular fbx import and it failed.
2. I tried importing using https://blendermarket.com/products/better-fbx-importer--exporter
3. Then I tried exporting as a gltf.

I don't know what would be the best way to solve this.

**Comment by julienduroure** [comment]
Maybe we can:
* open a ticket in blender repo to share import issue that generate the problem ?
* add some check to have an error message instead of a crash when there are some NaN ?

**Comment by fire** [comment]
The blend shape being nan problem hasn't blocked me some time. So create a new issue for your problem.
