### ISSUE TITLE
Importing glb file fails in Blender 2.91

### ISSUE THREAD

**Issue by beyChill** [KhronosGroup/glTF-Blender-IO#1310]
**Describe the bug**
Fresh install of Blender.  I'm unable to import gltf/glb files that I create and unable to import glb files from this github, https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle

**To Reproduce**
1. Start a new general project. 
2. Export the cube as glb or gltf
3. Import the file exported in step 2
4. See error:

Python: Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/__init__.py", line 974, in execute
    return self.import_gltf2(context)
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/__init__.py", line 988, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/__init__.py", line 1002, in unit_import
    gltf_importer.read()
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py", line 144, in read
    gltf, self.glb_buffer = self.load_glb(content)
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py", line 114, in load_glb
    gltf = glTFImporter.load_json(json_bytes)
  File "/usr/share/blender/2.91/scripts/addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py", line 64, in load_json
    return json.loads(bytes(content), encoding='utf-8', parse_constant=bad_constant)
  File "/usr/lib64/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

location: <unknown location>:-1
bpy.ops.import_scene.gltf(filepath="/home/jay/github/none.gltf", files=[{"name":"none.gltf", "name":"none.gltf"}], loglevel=50)

**Expected behavior**
Import glb file without problem especially when the export is default everything from a new install. No changes were made to export. 

My files:
[github.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5790266/github.zip)

 - OS: Fedora 33
 - Blender Version 2.91, build date: 2020-11-27

**Comment by scurest** [comment]
This is #1295. It should work with a Blender downloaded from https://builder.blender.org/download/.

**Comment by beyChill** [comment]
Yes, the problem does not exist in 2.92 Alpha.
