### ISSUE TITLE
cannot export in .glb fomart when the dacro compression is on

### ISSUE THREAD

**Issue by Noahmuiruri** [KhronosGroup/glTF-Blender-IO#1363]
i get the following error:(blender 2.92)
trying to export a model with 2 million polys...
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\__init__.py", line 575, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 79, in __gather_gltf
    gltf2_io_draco_compression_extension.encode_scene_primitives(scenes, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_draco_compression_extension.py", line 67, in encode_scene_primitives
    __traverse_node(node, lambda node: __encode_node(node, dll, export_settings))
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_draco_compression_extension.py", line 71, in __traverse_node
    f(node)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_draco_compression_extension.py", line 67, in <lambda>
    __traverse_node(node, lambda node: __encode_node(node, dll, export_settings))
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_draco_compression_extension.py", line 81, in __encode_node
    __encode_primitive(primitive, dll, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_draco_compression_extension.py", line 107, in __encode_primitive
    dll.encoderSetIndices(encoder, indices.component_type, indices.count, indices.buffer_view.data)
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

**Comment by donmccurdy** [comment]
Appears to be the same issue as #1351.
