### ISSUE TITLE
AttributeError: 'NoneType

### ISSUE THREAD

**Issue by kickus** [KhronosGroup/glTF-Blender-IO#1382]
Trying to export to gltf, but failing due to error.  I've got no clue why. Attached the blend file.

 - OS: macOS
 - Blender Version 2.92

Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/__init__.py", line 575, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 72, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 60, in __gather_scene
    blender_scene, None, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 46, in gather_node
    node = __gather_node(blender_object, library, blender_scene, dupli_object_parent, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 74, in __gather_node
    mesh = __gather_mesh(blender_object, library, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 271, in __gather_mesh
    return __gather_mesh_from_nonmesh(blender_object, library, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 378, in __gather_mesh_from_nonmesh
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 42, in gather_mesh
    name=__gather_name(blender_mesh, library, vertex_groups, modifiers, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 119, in __gather_name
    return blender_mesh.name
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

[tg7000 2.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6369738/tg7000.2.blend.zip)

**Comment by julienduroure** [comment]
Confirmed.
You have a curve object (Curve.001) with a single point, and not segment. We will add check to avoid error, but for a quick workaround for now, you can delete this object.

**Comment by julienduroure** [comment]
Fix 1382

**Comment by kickus** [comment]
Thanks!
