### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor location: <unknown location>

### ISSUE THREAD

**Issue by Konradrundfunk** [KhronosGroup/glTF-Blender-IO#1437]
**Describe the bug**
When exporting a specific .blend file I get this error `OSError: [Errno 9] Bad file descriptor location: <unknown location>
`. The standart test file is working fine. 
Full log:
```Python: Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/__init__.py", line 626, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 75, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 57, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 46, in gather_node
    node = __gather_node(blender_object, library, blender_scene, dupli_object_parent, export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 74, in __gather_node
    mesh = __gather_mesh(blender_object, library, export_settings)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 342, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 44, in gather_mesh
    primitives=__gather_primitives(blender_mesh, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 130, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 50, in gather_primitives
    blender_primitives = __gather_cache_primitives(blender_mesh, library, blender_object,
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 97, in __gather_cache_primitives
    blender_primitives = gltf2_blender_extract.extract_primitives(
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py", line 25, in extract_primitives
    print_console('INFO', 'Extracting primitive: ' + blender_mesh.name)
  File "/usr/share/blender/2.93/scripts/addons/io_scene_gltf2/io/com/gltf2_io_debug.py", line 57, in print_console
    print(get_timestamp() + " | " + level + ': ' + output)
OSError: [Errno 9] Bad file descriptor

location: <unknown location>:-1

```

**To Reproduce**
1. clicked on export in the File menu 
2. selected a folder and than sat the format to .glb
3.  deselcted every additional export option to prevent a recource blocking 
4. clicked on Export glFT 2.0

**Expected behavior**
Return a glb file in the selected output folder.

**Version**
 - OS:  5.12.15-arch1-1 
 - Blender Version 2.93.1

**Blend file and textures**

[Noaa15.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6843631/Noaa15.zip) (Modell royalty free)

**Comment by julienduroure** [comment]
I cannot reproduce this error, but have this one instead:
```
Python: Traceback (most recent call last):
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/__init__.py", line 637, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 71, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 111, in __fix_json
    fixed[key] = __fix_json(value)
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 115, in __fix_json
    fixed.append(__fix_json(value))
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 111, in __fix_json
    fixed[key] = __fix_json(value)
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 115, in __fix_json
    fixed.append(__fix_json(value))
  File "/usr/local/bin/blender-2.93.1-linux-x64/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 118, in __fix_json
    if int(obj) == obj:
OverflowError: cannot convert float infinity to integer
```

**Comment by Konradrundfunk** [comment]
Any updates on that matter?

**Comment by julienduroure** [comment]
#1458 will solve my issue (you probably have some non valid meshes).
File seems to export correctly, without any traceback. I cannot reproduce your issue.
Didn't check yet why I can't see anything in online viewer)

**Comment by Konradrundfunk** [comment]
Ok seams fair enougth gonna close this than.
