### ISSUE TITLE
Failure exporting to GLB with animated armature

### ISSUE THREAD

**Issue by diogodutra** [KhronosGroup/glTF-Blender-IO#1478]
**Describe the bug**
Blender results in error when trying to export a rigged animated model to glb.

**To Reproduce**
1. File > Export > glTF 2.0
2. Tried all possible combinations of export options (checkboxes), always selecting glb format

**Expected behavior**
https://sandbox.babylonjs.com/ should successfully load the exported glb and show all the animation options on the lower bar. However, the model is not even created at all (see error message below). I found out that deleting the drivers results in successful export, but all animations are lost.

**.blend file/ .gltf**
Model + zipped texture from https://smutba.se/project/31506/.

**Version**
 - OS: Windows 10 from Surface Pro 7
 - Blender Version 2.93.5

**Additional context**
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\__init__.py", line 626, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 75, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 39, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 83, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(_blender_object, merged_tracks, len(animations), export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 76, in gather_animations
    animation = __gather_animation(blender_action, blender_object, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 114, in __gather_animation
    channels=__gather_channels(blender_action, blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 149, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 103, in gather_animation_channels
    channel = __gather_animation_channel(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 202, in __gather_animation_channel
    sampler=__gather_sampler(channels, blender_object, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, action_name, driver_obj),
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 254, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 70, in gather_animation_sampler
    output=__gather_output(channels,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 338, in __gather_output
    bone = gltf2_blender_get.get_object_from_datapath(blender_object_if_armature, object_path)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_get.py", line 37, in get_object_from_datapath
    prop = blender_object.path_resolve(data_path)
ValueError: Object.path_resolve("key_blocks["COR.thigh_up_L"]") could not be resolved

location: <unknown location>:-1
```

**Comment by julienduroure** [comment]
Can you please test with blender 3.0 alpha ( https://builder.blender.org/download/daily/ ) ?
This is already solved in master. (duplicate of #1415)

**Comment by diogodutra** [comment]
Solved. Thanks!

And sorry for the Github issue duplication.
