### ISSUE TITLE
Can't export during Edit Mode

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#151]
Steps to reproduce:

1. Launch Blender 2.80
2. Press the <kbd>TAB</kbd> key on the 3D window, to enter "Edit Mode"
3. File -> Export glTF

```
Traceback (most recent call last):
  File "..\addons\io_scene_gltf2\__init__.py", line 360, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 29, in save
    json, buffer = __export(export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 37, in __export
    __add_root_objects(exporter, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __add_root_objects
    scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 51, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 43, in gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 177, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh, vertex_groups, modifiers, skip_filter, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 37, in gather_mesh
    primitives=__gather_primitives(blender_mesh, vertex_groups, modifiers, export_settings),
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 85, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh, vertex_groups, modifiers, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 46, in gather_primitives
    None, blender_mesh, vertex_groups, modifiers, export_settings)
  File "..\addons\io_scene_gltf2\blender\exp\gltf2_blender_extract.py", line 631, in extract_primitives
    uv = blender_mesh.uv_layers[tex_coord_index].data[loop_index].uv
IndexError: bpy_prop_collection[index]: index 2 out of range, size 0

location: <unknown location>:-1
```

**Comment by UX3D-schmithuesen** [comment]
I referenced the wrong issue number there so this one is not fixed yet, sorry.
