### ISSUE TITLE
Error on importing GLB file

### ISSUE THREAD

**Issue by MedicOP** [KhronosGroup/glTF-Blender-IO#1623]
**Describe the bug**
Get this error when importing GLB file
```Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 1109, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 1137, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 1157, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 42, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 49, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 50, in create
    import_user_extensions('gather_import_scene_after_nodes_hook', gltf, gltf.data.scenes[gltf.data.scene], scene)
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1
```

**To Reproduce**
1. Import > GLB file
2. Error

**Expected behavior**
No error

**Screenshots**
Not applicable

**.blend file/ .gltf**
[camera.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8460144/camera.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 3.1.2

**Additional context**
It works fine in Blender 2.91

**Comment by MedicOP** [comment]
Maybe already fixed, seems to work after copying `addons/io_scene_gltf2` into my `scripts/addons/` folder

**Comment by scurest** [comment]
Yes, this was #1603, which is now fixed.

**Comment by julienduroure** [comment]
@yuzotova Please open a new ticket with your test file
