### ISSUE TITLE
Export is not available

### ISSUE THREAD

**Issue by InamuraJIN** [KhronosGroup/glTF-Blender-IO#1636]
Python: Traceback (most recent call last):
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 651, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 77, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 39, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 83, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(_blender_object, merged_tracks, len(animations), export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 77, in gather_animations
    animation = __gather_animation(blender_action, blender_object, export_settings)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 115, in __gather_animation
    channels=__gather_channels(blender_action, blender_object, export_settings),
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 152, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 139, in gather_animation_channels
    channel = __gather_animation_channel(
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 230, in __gather_animation_channel
    sampler = __gather_sampler(channels, blender_object, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, force_range, action_name, driver_obj, node_channel_is_animated)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 294, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 66, in gather_animation_sampler
    input = __gather_input(channels, blender_object_if_armature, non_keyed_values,
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 247, in __gather_input
    keyframes = gltf2_blender_gather_animation_sampler_keyframes.gather_keyframes(blender_object_if_armature,
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py", line 238, in gather_keyframes
    mat = get_bone_matrix(
  File "C:\Users\***\Documents\blender-3.1.0-windows-x64\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 94, in wrapper_bonecache
    return result[args[7]][pose_bone_if_armature.name]
KeyError: 1.0

location: <unknown location>:-1

**Comment by julienduroure** [comment]
Hello,
Can you please test with a recent build of 3.2 alpha?

**Comment by InamuraJIN** [comment]
I still get an error


Python: Traceback (most recent call last):
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\__init__.py", line 628, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 91, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 126, in gather_animations
    animation = __gather_animation(obj_uuid, blender_action, export_settings)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 169, in __gather_animation
    channels=__gather_channels(obj_uuid, blender_action, export_settings),
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 206, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 128, in gather_animation_channels
    channel = gather_animation_channel(
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 268, in gather_animation_channel
    sampler = __gather_sampler(channels, obj_uuid, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, force_range, action_name, driver_obj_uuid, node_channel_is_animated)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 336, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 59, in gather_animation_sampler
    input = __gather_input(channels, obj_uuid, is_armature, non_keyed_values,
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 243, in __gather_input
    keyframes, is_baked = gltf2_blender_gather_animation_sampler_keyframes.gather_keyframes(blender_obj_uuid,
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py", line 318, in gather_keyframes
    mat = get_bone_matrix(
  File "C:\Users\***\Documents\blender-3.2.0-alpha+master.c486da0238bd-windows.amd64-release\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 134, in wrapper_bonecache
    return result[cache_key_args[7]][pose_bone_if_armature.name]
KeyError: 1.0

**Comment by julienduroure** [comment]
Hello,
Can you please share the blend you are trying to export?
Thanks,

**Comment by julienduroure** [comment]
Confirmed.

But I don't have the same issue on my side.
Error come from using at the same time:
- export selection only
- always sampled is OFF

(Note that in your case, sampled with be forced in most cases, because channels don't have same number of keyframes)

**Comment by InamuraJIN** [comment]
What does it mean?
export selection only is ON/OFF
always sampled is ON/OFF
I have also tried copying and exporting to a new Blender, etc
But I can't export

**Comment by julienduroure** [comment]
Your problem occurs only when both export selection only is ON and always sampled is OFF.
Any other combination of these 2 parameters export are fine.
This will be fixed by #1638

**Comment by InamuraJIN** [comment]
Export errors even if "export selection only" is turned off

Python: Traceback (most recent call last):
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\__init__.py", line 651, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 63, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 77, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 39, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 83, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(_blender_object, merged_tracks, len(animations), export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 77, in gather_animations
    animation = __gather_animation(blender_action, blender_object, export_settings)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 115, in __gather_animation
    channels=__gather_channels(blender_action, blender_object, export_settings),
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 152, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Users\***\Documents\blender-3.0.0-windows-x64\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 45, in gather_animation_channels
    if blender_action.use_frame_range is True:
AttributeError: 'Action' object has no attribute 'use_frame_range'

location: <unknown location>:-1
