### ISSUE TITLE
I can not export animation from Blender to glTF

### ISSUE THREAD

**Issue by tssrkt** [KhronosGroup/glTF-Blender-IO#1693]
**Describe the bug**
When I export without animation it do it correctly. But with animation it gives this error:

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\__init__.py", line 628, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 91, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 128, in gather_animations
    animation = __gather_animation(obj_uuid, blender_action, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 171, in __gather_animation
    channels=__gather_channels(obj_uuid, blender_action, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 208, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 106, in gather_animation_channels
    channel = gather_animation_channel(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 266, in gather_animation_channel
    __target= __gather_target(obj_uuid, channels, export_settings, bake_bone, bake_channel, driver_obj_uuid)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 359, in __gather_target
    return gltf2_blender_gather_animation_channel_target.gather_animation_channel_target(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channel_target.py", line 29, in gather_animation_channel_target
    path=__gather_path(channels, blender_object, export_settings, bake_bone, bake_channel)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channel_target.py", line 92, in __gather_path
    target = [c for c in channels if c is not None][0].data_path.split('.')[-1]
IndexError: list index out of range
```

**To Reproduce**
1. Export glTF.
2. The Error.

**Expected behavior**
It should be exported!

**Screenshots**
https://prnt.sc/Nurs4KGP_3sQ

**.blend file/ .gltf**
[If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.](https://drive.google.com/file/d/1z6ItwiDhCnXrbXcUl2QorORm7g7xeLtL/view?usp=sharing)

**Version**
 - Windows 10 x64
 - Blender Version 3.2.1
 
**Additional context**
In 2.91 version was the same error

**Comment by tssrkt** [comment]
Trying to find solution: https://docs.blender.org/manual/en/3.2/addons/import_export/scene_gltf2.html
But no results...

**Comment by tssrkt** [comment]
> Hello, You have 3 invalid drivers on your model. Remove them will solve the issue.
> 
> I will add some checks to ignore invalid drivers.

Where are those drivers? I don't see there any drivers, I deleted all drivers.
Can you tell me what you mean telling drivers? Maybe names of drivers?
Where are those drivers? On mesh? On armature? I don't see there any drivers!

**Comment by julienduroure** [comment]
Here, on Unicorn_A mesh:
![image](https://user-images.githubusercontent.com/1696020/183248972-fa9b21f7-bef9-41a6-9eb3-e990ac14fefa.png)

**Comment by xixiluoke** [comment]
I also encountered this problem, how to find invalid drivers

**Comment by julienduroure** [comment]
@xixiluoke Can you please create a new ticket with your file attached?

**Comment by xixiluoke** [comment]
So sad, the company rules can not upload all kinds of files, can you tell me how to check
