### ISSUE TITLE
Failure on exporting lights with nodes

### ISSUE THREAD

**Issue by qwiglydee** [KhronosGroup/glTF-Blender-IO#171]
When a light has nodes, addon fails to export it.

```
Traceback (most recent call last):
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 354, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 29, in save
    json, buffer = __export(export_settings)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 38, in __export
    __add_root_objects(exporter, export_settings)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 53, in __add_root_objects
    scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 34, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 51, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, export_settings)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 40, in gather_node
    extensions=__gather_extensions(blender_object, export_settings),
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 114, in __gather_extensions
    export_settings
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 51, in wrapper_cached
    result = func(*args)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py", line 34, in gather_lights_punctual
    color=__gather_color(blender_lamp, export_settings),
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py", line 56, in __gather_color
    emission_node = __get_cycles_emission_node(blender_lamp)
  File "/opt/blender-2.8/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py", line 121, in __get_cycles_emission_node
    if isinstance(currentNode, bpy.types.ShaderNodeOutputLamp):
AttributeError: 'RNA_Types' object has no attribute 'ShaderNodeOutputLamp'
```

Proper node name is `ShaderNodeOutputLight`.
They were renamed at this commit:
https://developer.blender.org/rB74fd17e9d788394fa5bf781bb3e60bca7617b22c

**Comment by qwiglydee** [comment]
After fixing node name another exception occurs:
```
 File "/home/qmax/.local/share/blender-28/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py", line 35, in gather_lights_punctual
    intensity=__gather_intensity(blender_lamp, export_settings),
  File "/home/qmax/.local/share/blender-28/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py", line 70, in __gather_intensity
    gltf2_blender_search_node_tree.FilterByType(bpy.types.ShaderNodeLightFalloff)
  File "/home/qmax/.local/share/blender-28/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 96, in from_socket
    return __search_from_socket(start_socket, shader_node_filter, [])
  File "/home/qmax/.local/share/blender-28/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 82, in __search_from_socket
    for link in start_socket.links:
AttributeError: 'NoneType' object has no attribute 'links'
```

**Comment by qwiglydee** [comment]
Here are all three fixes I did to make it work:
[issue171.patch.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/2682989/issue171.patch.txt)
Tested only by visually inspecting gltf file.

**Comment by UX3D-schmithuesen** [comment]
@qwiglydee can you please attach an example `.blend` file?

**Comment by qwiglydee** [comment]
@julienduroure is running tests from `test` subdir enough to ensure it works in both versions?

**Comment by qwiglydee** [comment]
@UX3D-schmithuesen 
[test-node-light-b28.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2691029/test-node-light-b28.zip)
