### ISSUE TITLE
"Keep original" + packed images --> Error exporting to GLTF  Separate

### ISSUE THREAD

**Issue by timshannon** [KhronosGroup/glTF-Blender-IO#1727]
**Describe the bug**
With the update to blender 3.3.0 my I started getting errors on importing my blend files into Godot, which uses a command line script to export to GLTF, with the "Keep Original" setting set in the command line (https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_scene_importer_blend.cpp#L188).

If you have a blend file with a linked material (like from an asset library), this export throws an error:

```
Traceback (most recent call last):
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 69, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 35, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 246, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 61, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 147, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 83, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 60, in gather_material
    pbr_metallic_roughness, uvmap_actives_pbr_metallic_roughness = __gather_pbr_metallic_roughness(blender_material, orm_texture, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 344, in __gather_pbr_metallic_roughness
    return gltf2_blender_gather_materials_pbr_metallic_roughness.gather_material_pbr_metallic_roughness(
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 18, in gather_material_pbr_metallic_roughness
    base_color_texture, use_active_uvmap_base_color_texture, _ = __gather_base_color_texture(blender_material, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 97, in __gather_base_color_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(inputs[0], inputs, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 23, in gather_texture_info
    return __gather_texture_info_helper(primary_socket, blender_shader_sockets, 'DEFAULT', filter_type, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 44, in __gather_texture_info_helper
    index, factor = __gather_index(blender_shader_sockets, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 141, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets, export_settings)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/snap/blender/2790/3.3/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 31, in gather_texture
    source, factor = __gather_source(blender_shader_sockets, export_settings)
TypeError: cannot unpack non-iterable NoneType object

```

**To Reproduce**
Use the attached blender file, and export to GLTF with these settings:
![image](https://user-images.githubusercontent.com/1330485/190516061-26036ee3-4ad1-41d8-8dda-0c50e8fc4cdf.png)

**Expected behavior**
Should export without error.

**.blend file/ .gltf**
[cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9579298/cube.zip)

**Version**
 - OS: Linux (Ubuntu 22.04.1 LTS)
 - Blender Version 3.3.0 from ubuntu snap

Seems like a similar issue to https://github.com/KhronosGroup/glTF-Blender-IO/issues/1618

**Comment by julienduroure** [comment]
Confirmed
(Note that you didn't provide your asset library, so I can't use your test file)

More important note : using "keep original" is designed (requested by Godot team) to use original texture file. 
If files are not correctly setup, textures are not exported (example: not using correct ORM texture channels in 1 image).

I will fix the crash, but in case of packed images, texture will not be exported.
You will have to unpack your textures first, to have the correct setup of texture to be able to use "keep original".

**Comment by timshannon** [comment]
Good to know.  It should also be noted, that I'm not really using the exported textures, just using the names to reference the real material stored in a separate resource in Godot.  This type of scenario is perfect for the `placeholder` option, but Godot currently is throwing away the material names when that is used: https://github.com/godotengine/godot-proposals/issues/4343
