### ISSUE TITLE
bpy.ops.export_scene.gltf always error after Reload Scripts

### ISSUE THREAD

**Issue by dyn-do** [KhronosGroup/glTF-Blender-IO#1784]
**Describe the bug**
I am creating an addon that outputs meshes to GLB files with `bpy.ops.export_scene.gltf`.
It works fine as soon as I start Blender, but after I modify the source of my add-on, when I reload it with "Reload Scripts" and execute the process again, an error always occurs.

**To Reproduce**
1. Launch Blender.
2. Modify the add-on source calling `bpy.ops.export_scene.gltf`.
3. System > Reload Scripts
4. Run the addon.

**Expected behavior**
An error occurred and the GLB file is not output.

**Screenshots**
```
08:50:38 | INFO: Draco mesh compression is available, use library at C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\extern_draco.dll
08:50:38 | INFO: Starting glTF 2.0 export
08:50:38 | INFO: Extracting primitive: Body (merged).baked.004
08:50:38 | INFO: Primitives created: 1
08:50:38 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
08:50:38 | INFO: Draco encoder: Encoding mesh Body.003.
DracoEncoder | Preserve triangle order: yes
DracoEncoder | Encoded 5224 vertices, 20382 indices, raw size: 207932, encoded size: 91046, compression ratio: 2.28
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 840, in <lambda>
    result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 50, in from_dict
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 50, in <dictcomp>
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 96, in from_extension
    assert isinstance(x, dict)
08:50:38 | ERROR: An error occurred on line 35 in statement return f(x)
08:50:38 | ERROR: An error occurred on line 840 in statement result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
08:50:38 | ERROR: An error occurred on line 50 in statement return {k: f(v) for (k, v) in x.items()}
08:50:38 | ERROR: An error occurred on line 50 in statement return {k: f(v) for (k, v) in x.items()}
08:50:38 | ERROR: An error occurred on line 96 in statement assert isinstance(x, dict)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 27, in from_none
    assert x is None
08:50:38 | ERROR: An error occurred on line 35 in statement return f(x)
08:50:38 | ERROR: An error occurred on line 27 in statement assert x is None
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in <lambda>
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in from_list
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in <listcomp>
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in <lambda>
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 55, in to_class
    return x.to_dict()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 840, in to_dict
    result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
08:50:38 | ERROR: An error occurred on line 35 in statement return f(x)
08:50:38 | ERROR: An error occurred on line 1192 in statement result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
08:50:38 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
08:50:38 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
08:50:38 | ERROR: An error occurred on line 1192 in statement result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
08:50:38 | ERROR: An error occurred on line 55 in statement return x.to_dict()
08:50:38 | ERROR: An error occurred on line 840 in statement result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
08:50:38 | ERROR: An error occurred on line 45 in statement assert False
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 27, in from_none
    assert x is None
08:50:38 | ERROR: An error occurred on line 35 in statement return f(x)
08:50:38 | ERROR: An error occurred on line 27 in statement assert x is None
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
  Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\__init__.py", line 147, in execute
    ModifierToShapeOperates.export_gltf()
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\operates\ModifierToShapeOperates.py", line 182, in export_gltf
    bpy.ops.export_scene.gltf(filepath=glbPath,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

Error: Python: Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\__init__.py", line 147, in execute
    ModifierToShapeOperates.export_gltf()
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\operates\ModifierToShapeOperates.py", line 182, in export_gltf
    bpy.ops.export_scene.gltf(filepath=glbPath,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_ui\space_statusbar.py", line 8, in draw
    def draw(self, context):
KeyboardInterrupt
... truncated08:54:59 | INFO: Draco mesh compression is available, use library at C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\extern_draco.dll
08:54:59 | INFO: Starting glTF 2.0 export
08:54:59 | INFO: Extracting primitive: Body (merged).baked.006
08:54:59 | INFO: Primitives created: 1
08:54:59 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
08:54:59 | INFO: Extracting primitive: Face (merged).baked.004
08:54:59 | INFO: Primitives created: 1
08:54:59 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
08:54:59 | INFO: Draco encoder: Encoding mesh Body.004.
DracoEncoder | Preserve triangle order: yes
DracoEncoder | Encoded 5224 vertices, 20382 indices, raw size: 207932, encoded size: 91046, compression ratio: 2.28
08:54:59 | INFO: Draco encoder: Encoding mesh Face.003.
DracoEncoder | Preserve triangle order: yes
DracoEncoder | Encoded 2692 vertices, 13248 indices, raw size: 112640, encoded size: 53865, compression ratio: 2.09
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 840, in <lambda>
    result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 50, in from_dict
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 50, in <dictcomp>
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 96, in from_extension
    assert isinstance(x, dict)
08:54:59 | ERROR: An error occurred on line 35 in statement return f(x)
08:54:59 | ERROR: An error occurred on line 840 in statement result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
08:54:59 | ERROR: An error occurred on line 50 in statement return {k: f(v) for (k, v) in x.items()}
08:54:59 | ERROR: An error occurred on line 50 in statement return {k: f(v) for (k, v) in x.items()}
08:54:59 | ERROR: An error occurred on line 96 in statement assert isinstance(x, dict)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 27, in from_none
    assert x is None
08:54:59 | ERROR: An error occurred on line 35 in statement return f(x)
08:54:59 | ERROR: An error occurred on line 27 in statement assert x is None
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in <lambda>
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in from_list
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in <listcomp>
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in <lambda>
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 55, in to_class
    return x.to_dict()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 840, in to_dict
    result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
08:54:59 | ERROR: An error occurred on line 35 in statement return f(x)
08:54:59 | ERROR: An error occurred on line 1192 in statement result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
08:54:59 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
08:54:59 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
08:54:59 | ERROR: An error occurred on line 1192 in statement result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
08:54:59 | ERROR: An error occurred on line 55 in statement return x.to_dict()
08:54:59 | ERROR: An error occurred on line 840 in statement result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
08:54:59 | ERROR: An error occurred on line 45 in statement assert False
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 27, in from_none
    assert x is None
08:54:59 | ERROR: An error occurred on line 35 in statement return f(x)
08:54:59 | ERROR: An error occurred on line 27 in statement assert x is None
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
  Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\__init__.py", line 147, in execute
    ModifierToShapeOperates.export_gltf()
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\operates\ModifierToShapeOperates.py", line 182, in export_gltf
    bpy.ops.export_scene.gltf(filepath=glbPath,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

Error: Python: Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\__init__.py", line 147, in execute
    ModifierToShapeOperates.export_gltf()
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm-rig\operates\ModifierToShapeOperates.py", line 182, in export_gltf
    bpy.ops.export_scene.gltf(filepath=glbPath,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113
```

**.blend file/ .gltf**

**Version**
 - OS: Windows 11
 - Blender Version: 3.3.1

**Additional context**

**Comment by julienduroure** [comment]
Hello,
Does it occurs for any exported files (for default cube ?) ?
What option are you using? Seems you at least use Dravo compression.

What modification do you perform on source code ? What file do you modify?

I can't reproduce for now.

**Comment by dyn-do** [comment]
@julienduroure
Thank you for your reply.  
Sorry for the lack of information.  
My addons weren't causing the error.  
An error occurred in the blend file in the following.  
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9945055/test.zip)

1. File > Export > glTF 2.0
2. Check Geometry > Compression and Export.
2. System > Reload Scripts
3. Do 1. 2. again

This step will result in an error.
I've tried similar steps with FBX/DAE and no errors.

**Comment by julienduroure** [comment]
Confirmed

**Comment by julienduroure** [comment]
Hello,

Found the root cause : Extension class.
You can create a simplier test case with the default cube, and add some Transmission to Principled Shader (this will add 2 extension for transmission and IOR).

Seems that after reload, isinstance() is no more True for comparing `gltf2_io_extensions.Extension`. 
I don't know why :(

Replacing 

> if isinstance(node, gltf2_io_extensions.Extension):

By 

> if type(node).__name__ == gltf2_io_extensions.Extension.__name__:

solves the issue

https://github.com/KhronosGroup/glTF-Blender-IO/blob/f877995da23c10b8190b9a33ea5f32690485e82d/addons/io_scene_gltf2/blender/exp/gltf2_blender_gltf2_exporter.py#L322
