### ISSUE TITLE
Blender throws keyframe error when exporting as gltf with animations - Key.path_resolve could not be resolved

### ISSUE THREAD

**Issue by gmgm4321** [KhronosGroup/glTF-Blender-IO#1803]
Blender fails to export my 3d model with animations. This error is most probably my fault as I am inexperienced with blender and animations. Still can't find any way to fix the issue. The issue might also be related to the sample blender file that I am using.

`Python: Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\__init__.py", line 693, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 93, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 114, in gather_animations
    animation = __gather_animation(obj_uuid, blender_action, export_settings)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 164, in __gather_animation
    channels=__gather_channels(obj_uuid, blender_action, export_settings),
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 201, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 160, in gather_animation_channels
    channel = gather_animation_channel(
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 300, in gather_animation_channel
    sampler = __gather_sampler(channels, obj_uuid, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, force_range, action_name, driver_obj_uuid, node_channel_is_animated)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 368, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 59, in gather_animation_sampler
    input = __gather_input(channels, obj_uuid, is_armature, non_keyed_values,
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 243, in __gather_input
    keyframes, is_baked = gltf2_blender_gather_animation_sampler_keyframes.gather_keyframes(blender_obj_uuid,
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py", line 357, in gather_keyframes
    mat = get_object_matrix(blender_obj_uuid,
  File "D:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 102, in wrapper_objectcache
    return func.__objectcache[cache_key_args[0]][cache_key_args[1]][cache_key_args[4]]
KeyError: 356.79998779296875
`
To Reproduce
1.Steps to reproduce the behavior:

2.Open my model in Blender 3.4.0
Export as gltf with animation export turned on

.blend file/ .gltf
[used this model](https://sketchfab.com/3d-models/auguri-2019-merry-christmas-2019-fd2951e29c6f4ae499f368a35475a8b7)]

**Comment by julienduroure** [comment]
Confirmed.
Linked to frame that are not integer.

Workaround for now : select all your keyframes in dopsheet, and Key > Snap > Snap Selection to nearest frame

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890
