### ISSUE TITLE
I want to export a file in gltf format, but the following error appears: AttributeError: 'NoneType' object has no attribute 'node tree'  

### ISSUE THREAD

**Issue by nymph1mao** [KhronosGroup/glTF-Blender-IO#1871]
Full error:

Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\__init__.py", line 693, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 69, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 38, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 246, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 61, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 147, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 83, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 60, in gather_material
    pbr_metallic_roughness, uvmap_actives_pbr_metallic_roughness = __gather_pbr_metallic_roughness(blender_material, orm_texture, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 344, in __gather_pbr_metallic_roughness
    return gltf2_blender_gather_materials_pbr_metallic_roughness.gather_material_pbr_metallic_roughness(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 18, in gather_material_pbr_metallic_roughness
    base_color_texture, use_active_uvmap_base_color_texture, _ = __gather_base_color_texture(blender_material, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 100, in __gather_base_color_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(inputs[0], inputs, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 23, in gather_texture_info
    return __gather_texture_info_helper(primary_socket, blender_shader_sockets, 'DEFAULT', filter_type, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 42, in __gather_texture_info_helper
    tex_transform, tex_coord, use_active_uvmap = __gather_texture_transform_and_tex_coord(primary_socket, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 172, in __gather_texture_transform_and_tex_coord
    if material.node_tree == node_tree:
AttributeError: 'NoneType' object has no attribute 'node_tree'

Version

OS: Windows 11
Blender Version 3.4

Blender file, textures, fonts: https://mega.nz/file/l6QjwLqb#vo_rQCiGtj1ftEXLQnkzuyeUis0O8AuwHjnvSvnJ2Ns

**Comment by scurest** [comment]
As stated in the issue template, you need to attach the .blend file.

**Comment by nymph1mao** [comment]
Blender file, textures, fonts:  https://mega.nz/file/l6QjwLqb#vo_rQCiGtj1ftEXLQnkzuyeUis0O8AuwHjnvSvnJ2Ns

**Comment by nymph1mao** [comment]
> As stated in the issue template, you need to attach the .blend file.

done :)

**Comment by scurest** [comment]
2GB is way too big for me. You should simplify it as much as possible by deleting anything you can without the bug going away.

Maybe someone else will check though.

**Comment by nymph1mao** [comment]
> 2GB is way too big for me. You should simplify it as much as possible by deleting anything you can without the bug going away.
> 
> Maybe someone else will check though.

Хорошо, все будет сделано, но файл упростить смогу только завтра

**Comment by nymph1mao** [comment]
> 2GB is way too big for me. You should simplify it as much as possible by deleting anything you can without the bug going away.
> 
> Maybe someone else will check though.

Okay, it will be done, but I can simplify the file only tomorrow

**Comment by scurest** [comment]
Actually I think this is the same as #1846, which means it should already be fixed. You can try downloading 3.5 Beta/3.6 Alpha from https://builder.blender.org/download/daily/ and see.

**Comment by nymph1mao** [comment]
> Actually I think this is the same as #1846, which means it should already be fixed in the latest version. You can try downloading 3.5 Beta/3.6 Alpha from https://builder.blender.org/download/daily/ and see.

I downloaded version 3.5 and everything worked. Thanks for the help.
