### ISSUE TITLE
Python error when trying to export an animated glb file.

### ISSUE THREAD

**Issue by Robin-Penot** [KhronosGroup/glTF-Blender-IO#1872]
Hi, I have this error message when im trying to export an animated glb file : 

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 93, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 131, in gather_animations
    animation = __gather_animation(obj_uuid, blender_action, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 174, in __gather_animation
    channels=__gather_channels(obj_uuid, blender_action, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 211, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 128, in gather_animation_channels
    channel = gather_animation_channel(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 268, in gather_animation_channel
    sampler = __gather_sampler(channels, obj_uuid, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, force_range, action_name, driver_obj_uuid, node_channel_is_animated)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 336, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 59, in gather_animation_sampler
    input = __gather_input(channels, obj_uuid, is_armature, non_keyed_values,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 243, in __gather_input
    keyframes, is_baked = gltf2_blender_gather_animation_sampler_keyframes.gather_keyframes(blender_obj_uuid,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py", line 356, in gather_keyframes
    mat = get_object_matrix(blender_obj_uuid,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 92, in wrapper_objectcache
    return result[cache_key_args[0]][cache_key_args[1]][cache_key_args[4]]
KeyError: 1.0

I tried exporting the glb file without the animation and it worked. The thing is that Blender is new to me so i really don't know how to resolve this problem.

My animation is juste a plateform moving up, stops for a few secondes and then going back down.

Tell me if you need more informations about the issue or the file I am using.

Thank you for your help and have a good day.

**Comment by Robin-Penot** [comment]
I also tried to redo all the animation on a new object and it shows the same issue

**Comment by Robin-Penot** [comment]
I finally resolved it, I only needed to select gltf embedded when exporting (I think I tried it before and didn't work but ok...) I hope this helps :)
