### ISSUE TITLE
Blender to Source Rig 'NoneType' object has no attribute 'action'

### ISSUE THREAD

**Issue by Jinofski** [KhronosGroup/glTF-Blender-IO#1878]
Heyyo,

I'm trying to export a character model to recompile into a GMod model, but for some reason I keep getting this error message. I was able to export this model previously without issue, I don't know what caused it, and I am extremely new to this whole pipeline, so any help would be greatly appreciated <3

Python: Traceback (most recent call last):
  File "C:\Users\violi\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_valvesource\export_smd.py", line 220, in execute
    else: self.exportId(context, collection)
  File "C:\Users\violi\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_valvesource\export_smd.py", line 551, in exportId
    self.files_exported += write_func(id, bake_results, self.sanitiseFilename(export_name), path)
  File "C:\Users\violi\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_valvesource\export_smd.py", line 1037, in writeSMD
    anim_len = animationLength(ad) + 1 # frame 0 is a frame too...
  File "C:\Users\violi\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_valvesource\utils.py", line 312, in animationLength
    if ad.action:
AttributeError: 'NoneType' object has no attribute 'action'

![Rigerror](https://user-images.githubusercontent.com/127492718/224287056-4592b4b2-1f0d-4baf-9ed5-c4bb3ca1396e.png)

**Comment by julienduroure** [comment]
Hello,
Not sure how you find this repository, but we are here developping  Blender glTF I/O.
Seems your are not trying to export glTF using our addon.
Please contact the developer of the io_scene_valvesource addon.
Thanks!
