### ISSUE TITLE
RuntimeError: Error: Image 'image22_001.png.001' does not have any image data while exporting image sequence animation as glb file

### ISSUE THREAD

**Issue by gentlesz** [KhronosGroup/glTF-Blender-IO#1910]
Issue:
adding an image sequence to a plane as image texture named 'image_001.png' 'image_002.png' 'image_003.png' 'image_004.png' and exporting it as glb returns the following error. 

have tried removing the png from the file name, removing the ### from the file name, setting output properties to different options but same error.

version used:

macOS : 13.3.1 (22E261)
blender : 3.5.0

error:

Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/__init__.py", line 718, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 69, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 38, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 246, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 61, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 147, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 83, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 60, in gather_material
    pbr_metallic_roughness, uvmap_actives_pbr_metallic_roughness = __gather_pbr_metallic_roughness(blender_material, orm_texture, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 349, in __gather_pbr_metallic_roughness
    return gltf2_blender_gather_materials_pbr_metallic_roughness.gather_material_pbr_metallic_roughness(
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 18, in gather_material_pbr_metallic_roughness
    base_color_texture, use_active_uvmap_base_color_texture, _ = __gather_base_color_texture(blender_material, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 100, in __gather_base_color_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(inputs[0], inputs, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 23, in gather_texture_info
    return __gather_texture_info_helper(primary_socket, blender_shader_sockets, 'DEFAULT', filter_type, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 44, in __gather_texture_info_helper
    index, factor = __gather_index(blender_shader_sockets, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 141, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 31, in gather_texture
    source, factor = __gather_source(blender_shader_sockets, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 83, in __gather_source
    return gltf2_blender_gather_image.gather_image(blender_shader_sockets, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 47, in gather_image
    buffer_view, factor_buffer_view = __gather_buffer_view(image_data, mime_type, name, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 101, in __gather_buffer_view
    data, factor = image_data.encode(mime_type, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 136, in encode
    return self.__encode_happy(export_settings), None
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 146, in __encode_happy
    return self.__encode_from_image(self.blender_image(), export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 228, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format, export_settings)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 242, in _encode_temp_image
    tmp_image.save()
RuntimeError: Error: Image 'image_001.png.001' does not have any image data

**Comment by julienduroure** [comment]
Hello,
Note that sequence images can't be exported as texture, as glTF core specification can't manage it.
But, we have to avoid crash in that case.
I can not reproduce using sequence image setup like this:
![image](https://user-images.githubusercontent.com/1696020/232507846-d6733c54-925b-48cb-aafb-4e7c15a6f2ad.png)

Has requested in bug template, please provide the .blend file (with images packed) or .blend and images needed to reproduce the issue.

**Comment by gentlesz** [comment]
[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11251231/Archive.zip)
have zipped the .blend file which contains a cube with 3 images as sequence animation on it. Exporting leads to the error mentioned above. also attached the 3 image files with the same names producing the error.

what would be the best way to place an animation sequence on a glb file before or after exporting? I have been self learning and trying and testing myself and everywhere points to blender as the best option. also tried video texture, images as planes and placing all the sequence on top of each other but was not able to animate (still looking around).

Any pointers would be great, thanks!

**Comment by julienduroure** [comment]
Ok, I can now reproduce.

You can not plug an image texture directly into Output Material node. You must use a shader node (like Principled Shader BSDF).
I suggest you to watch some tutorial about how to create materials in Blender.

Anyway, sequence images or movie textures are not part of glTF specification, so you can not export glb with sequences or movie.

Setting this ticket as bug, as you must be sure that this setup is ignored instead of crash.

**Comment by gentlesz** [comment]
with just a single image as texture, IT IS possible to export glb with texture without Shader BSDF.

actually it seems only possible if the bsdf material is deleted

**Comment by julienduroure** [comment]
You can retrieve some example in documentation:
https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#exported-materials

**Comment by scurest** [comment]
You can plug an Image Texture node directly into the output, it exports as unlit (see all possible unlit node setups [here](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1209#issuecomment-693700508)).

**Comment by donmccurdy** [comment]
Keyframed visibility cannot be exported. Closest supported thing would be to scale the planes with discrete step interpolation. If you can create the sequence of planes (with names like `plane_001` etc.) and export that, then you can add the animation with:

```
npm install --global @gltf-transform/cli

gltf-transform sequence input.glb output.glb --pattern "plane_*" --fps 10
```

https://gltf-transform.donmccurdy.com/cli.html

There's probably a way to do that last part in Blender too, but I'm not sure how.

**Comment by JonaNorman** [comment]
I'm also looking for a way to make gltf support sequence frame animation, can anyone help me？

**Comment by julienduroure** [comment]
Hello,
glTF specification does not support texture sequence animation.
Let's keep this ticket about the initial issue : avoid to crash when there is a texture sequence image.
