### ISSUE TITLE
glTF fails to import with "Array length mismatch" error, when using smooth and merge_vertices

### ISSUE THREAD

**Issue by garyo** [KhronosGroup/glTF-Blender-IO#1927]
**Describe the bug**

Using a nightly linux blender build from the site, importing a certain glTF object with smooth shading and vertex merging fails to import with an error and traceback.

**To Reproduce**
* Install Blender 3.6.0 Beta (hash 52f991b1a9b3 built 2023-05-21 23:34:10)  or a nightly build from the site
* Run the following python code using the blender python console `$BLENDER -b --python-console`
```python
import bpy
path="cartoon-cartoon-F1FDA60C-64D4-48E5-8645-FA98F5B63E06.glb"
bpy.ops.import_scene.gltf(filepath=path, import_shading='SMOOTH', merge_vertices=True)
```
* See error in python console:
```
Error: Array length mismatch (expected 19150, got 19170)
RuntimeError: internal error setting the array
> /home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py(455)do_primitives()
-> blender_attribute.data.foreach_set('value', attribute_data[idx].flatten())
Traceback (most recent call last):
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1539, in execute
    return self.import_gltf2(context)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1572, in import_gltf2
    return self.unit_import(self.filepath, import_settings)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1587, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 34, in create
    BlenderGlTF._create(gltf)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 41, in _create
    BlenderScene.create(gltf)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 36, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 30, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 51, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 228, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 24, in create
    return create_mesh(gltf, mesh_idx, skin_idx)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 45, in create_mesh
    do_primitives(gltf, mesh_idx, skin_idx, mesh, tmp_ob)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 455, in do_primitives
    blender_attribute.data.foreach_set('value', attribute_data[idx].flatten())
RuntimeError: internal error setting the array
Error: Python: Traceback (most recent call last):
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1539, in execute
    return self.import_gltf2(context)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1572, in import_gltf2
    return self.unit_import(self.filepath, import_settings)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1587, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.pyTraceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1539, in execute
    return self.import_gltf2(context)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1572, in import_gltf2
    return self.unit_import(self.filepath, import_settings)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/__init__.py", line 1587, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 34, in create
    BlenderGlTF._create(gltf)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 41, in _create
    BlenderScene.create(gltf)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 36, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 30, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 51, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 228, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 24, in create
    return create_mesh(gltf, mesh_idx, skin_idx)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 45, in create_mesh
    do_primitives(gltf, mesh_idx, skin_idx, mesh, tmp_ob)
  File "/home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 455, in do_primitives
    blender_attribute.data.foreach_set('value', attribute_data[idx].flatten())
RuntimeError: internal error setting the array
Location: /home/garyo/dss/product/horizon/ext-sources/blender/blender-builds/blender-3.6.0-beta+v36.52f991b1a9b3-linux.x86_64-release/3.6/scripts/modules/bpy/ops.py:113

... truncated
```

**Expected behavior**
The gltf file should load without error.

**Screenshots**
N/A

**.blend file/ .gltf**
[cartoon-cartoon-F1FDA60C-64D4-48E5-8645-FA98F5B63E06.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11534456/cartoon-cartoon-F1FDA60C-64D4-48E5-8645-FA98F5B63E06.zip)

**Version**
 - OS: linux
 - Blender 3.6.0 Beta (hash 52f991b1a9b3 built 2023-05-21 23:34:10)

**Additional context**
This used to work on Blender 3.1, but I haven't tried any intervening versions.
Note that the gltf file is valid; it passes the validators with no issues.
Both ` import_shading='SMOOTH'` and `merge_vertices=True` are required to see the issue. Removing either of those args from the import allows the glTF to import successfully.

**Comment by julienduroure** [comment]
Confirmed.
In this PR #1781 (add importing custom attribute feature), merging vertices options is not taken into account.
