### ISSUE TITLE
Error when exporting NLA tracks with same name

### ISSUE THREAD

**Issue by Xyotic** [KhronosGroup/glTF-Blender-IO#1951]
**Describe the bug**
When exporting NLA tracks whith same names, the exporter crashes.

**To Reproduce**
1. Create two simple animations on an armature
2. Push the animations down to th NLA stack
3. Give both tracks the same name
4. Export the armature as .glft/.glb with animation mode set to NLA tracks

**Expected behavior**
Export should succeed and output a gltf file with one animation consisting of the two tracks blended together.

**Screenshots**
![grafik](https://github.com/KhronosGroup/glTF-Blender-IO/assets/8405059/820056ac-4c2e-4808-9afe-91c8d9df8ea2)
![grafik](https://github.com/KhronosGroup/glTF-Blender-IO/assets/8405059/0d94793b-91c0-4ea2-851b-8c11708e2791)

**Version**
 - OS: Windows 11
 - Blender Version [3.6, 4.0 alpha]

**Comment by julienduroure** [comment]
Hello,
I can not reproduce with something that looks similar.
As requested in issue template, please always provide your test case.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/da630fb9-cfb6-4065-a1a0-74c346d3352e)


About settings 2 tracks with same same for a same object : If your actions have same channels keyed, we can't merge them, and then some channels will be omitted at export.
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/1f63955e-5446-47ab-ab9b-db5dc7ccdf11)

**Comment by Xyotic** [comment]
Seems like this doesnt happen on a fresh project.
Im trying to narrow it down but so far without luck.
Can't share the blend files since the model is for a commercial project.
Im getting these errors if i look into the terminal output:

>   File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1178, in <lambda>
    result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in from_list
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in <listcomp>
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1178, in <lambda>
    result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 55, in to_class
    return x.to_dict()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 386, in to_dict
    result["samplers"] = from_list(lambda x: to_class(AnimationSampler, x), self.samplers)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in from_list
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 60, in <listcomp>
    return [f(y) for y in x]
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 386, in <lambda>
    result["samplers"] = from_list(lambda x: to_class(AnimationSampler, x), self.samplers)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 54, in to_class
    assert isinstance(x, c)
14:15:10 | ERROR: An error occurred on line 35 in statement return f(x)
14:15:10 | ERROR: An error occurred on line 1178 in statement result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
14:15:10 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
14:15:10 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
14:15:10 | ERROR: An error occurred on line 1178 in statement result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
14:15:10 | ERROR: An error occurred on line 55 in statement return x.to_dict()
14:15:10 | ERROR: An error occurred on line 386 in statement result["samplers"] = from_list(lambda x: to_class(AnimationSampler, x), self.samplers)
14:15:10 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
14:15:10 | ERROR: An error occurred on line 60 in statement return [f(y) for y in x]
14:15:10 | ERROR: An error occurred on line 386 in statement result["samplers"] = from_list(lambda x: to_class(AnimationSampler, x), self.samplers)
14:15:10 | ERROR: An error occurred on line 54 in statement assert isinstance(x, c)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 35, in from_union
    return f(x)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 27, in from_none
    assert x is None
14:15:10 | ERROR: An error occurred on line 35 in statement return f(x)
14:15:10 | ERROR: An error occurred on line 27 in statement assert x is None
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\__init__.py", line 852, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 34, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 59, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1178, in to_dict
    result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
 AssertionError

Any idea what could cause these errors?
Maybe I'll be able to replicate it if i know where to look.

Also, shoudn't the expected behaviour of the export be a merged animation according to the tracks blending options, even if they use the same channels?

**Comment by julienduroure** [comment]
Hello,
Sorry, but the error is not enough information to investigate the issue.
You can either:
- trying to replicate the issue on a new file
- send the file to me by email with or without deteriorating the content

About NLA use:
The default option is "Action". That means that NLA tracks are used as an action library, without any blending.
You can use "track" node. This should export tracks (with modifiers on tracks) and merging using Blending. This option is quite new and still experimental. Any test case with issue is welcome :)

**Comment by Xyotic** [comment]
I attached the file with everything removed except the armature and two animations.
Everything should be setup to replicate the issue.

Just select the armature and hit export to gltf
"NLA Tracks" should be selected in the export settings.
I hope this helps. Please let me know if you need more information.

[Issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12062755/Issue.zip)

**Comment by julienduroure** [comment]
Hello,
I can now reproduce.

- All your tracks are in "Replace" blending mode. That means, no blending. glTF exporter will try to export 2 different animations, and then, merge them into a single one because of the name. During glTF merging, some channels will be ignored, because set multiple times. The trackback happen if some channels have exactly same values (same frames/same values). I will commit a fix to avoid crash, even if some channels are ignored

- If you want to combine / add some tracks, you should change Blending mode on your upper track. glTF will then bake result of your group of tracks, and will try to export only 1 animation.
