### ISSUE TITLE
gltf Export fails with Animation Mode set to NLA Tracks on specific files

### ISSUE THREAD

**Issue by dasfrodo** [KhronosGroup/glTF-Blender-IO#1998]
**Describe the bug**
Export of a gltf / glb file fails when "Animation mode" is set to "NLA-Tracks". **This doesn't happen with every file, but specifically with a file we're using which I unfortunately cannot attach here, due to NDA.** I could not reproduce it with any testfile yet.

The same file exports without issue in Blender 3.3.1. I suspect it has to do with the reworked interface and/or other changes that happened between these versions.

I can assure you that the file contains nothing special. It's just a couple of linked collections from other files, one of which has a relatively simple armature (not a character).

**To Reproduce**
1. Open Blender file with NLA animations in 3.6.2
2. Export with "Animation mode" set to "NLA-Tracks", everything else on default
3. Export fails with Python error

**Expected behavior**
File exports without error.

**Version**
 - OS: Windows 10 Pro 19045.3448
 - Blender Version 3.6.2

**Additional context**

The Python error:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\__init__.py", line 852, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 34, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 51, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 65, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 32, in gather_gltf2
    animations += gather_animations(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\gltf2_blender_gather_animations.py", line 21, in gather_animations
    return gather_tracks_animations(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\gltf2_blender_gather_tracks.py", line 26, in gather_tracks_animations
    animations_, merged_tracks = gather_track_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\gltf2_blender_gather_tracks.py", line 125, in gather_track_animations
    animation = bake_animation(obj_uuid, track_name, export_settings, mode=on_type)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\gltf2_blender_gather_animation_utils.py", line 169, in bake_animation
    animation = gather_action_object_sampled(obj_uuid, None, animation_key, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_action_sampled.py", line 18, in gather_action_object_sampled
    channels=__gather_channels(object_uuid, blender_action.name if blender_action else cache_key, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_action_sampled.py", line 42, in __gather_channels
    return gather_object_sampled_channels(object_uuid, blender_action_name, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_channels.py", line 32, in gather_object_sampled_channels
    channel = gather_sampled_object_channel(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 35, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_channels.py", line 61, in gather_sampled_object_channel
    sampler = __gather_sampler(obj_uuid, channel, action_name, node_channel_is_animated, node_channel_interpolation, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_channels.py", line 104, in __gather_sampler
    return gather_object_sampled_animation_sampler(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 35, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_sampler.py", line 27, in gather_object_sampled_animation_sampler
    keyframes = __gather_keyframes(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_sampler.py", line 62, in __gather_keyframes
    keyframes = gather_object_sampled_keyframes(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 35, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\object\gltf2_blender_gather_object_keyframes.py", line 31, in gather_object_sampled_keyframes
    mat = get_cache_data(
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 97, in wrapper_objectcache
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\exp\animation\sampled\gltf2_blender_gather_animation_sampling_cache.py", line 100, in get_cache_data
    if 'bone' not in data[obj_uuid][obj_uuid].keys():
KeyError: '64d010e6-d72d-4b95-bc86-d1e5e53145be'
```

**Comment by julienduroure** [comment]
Hello,
Sorry, but without a way to reproduce the error, I will not be able to investigate this issue, that is specific to the file.
You can either:
- Send it to me by email, if you don't want to share it online
- Trying to replicate the issue in a simple example file
- Replace meshes that are under DNA with some other meshes (and be sure that the bug is still there)

**Comment by dasfrodo** [comment]
> Hello, Sorry, but without a way to reproduce the error, I will not be able to investigate this issue, that is specific to the file. You can either:
> 
> * Send it to me by email, if you don't want to share it online
> * Trying to replicate the issue in a simple example file
> * Replace meshes that are under DNA with some other meshes (and be sure that the bug is still there)

I just sent you an E-Mail to your contact adress on your website. I hope that's the correct channel.
I have reduced the file as much as I can. I suspect the issue is (somehow) that the Helpercircle has an animation, but no bones. At least that's what I can gather from playing with the file, the Python error and the fact that the file exports perfectly after deleting that object.

**Comment by julienduroure** [comment]
Really simple file to reproduce the issue

[untitled.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12610199/untitled.blend.zip)
