### ISSUE TITLE
Blender 2.8 Beta GLTF Exporter Errors

### ISSUE THREAD

**Issue by sketchpunk** [KhronosGroup/glTF-Blender-IO#202]
Trying to export some models and some don't seem to work. In export, i check off everything except for 
General > +Y Up
and
Meshes > UVs and Normals

I would like to export the skinning stuff too, but it can't export just the mesh. I've attached the blend file in a zip file. Its a model of Venom.

[Venom_Final.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2722747/Venom_Final.zip)

location: <unknown location>:-1
04:15:36 | INFO: Starting glTF 2.0 export
04:15:36 | INFO: Extracting primitive
04:15:36 | DEBUG: Adding primitive without splitting. Indices: 42 Vertices: 18
04:15:36 | INFO: Primitives created: 1
04:15:36 | INFO: Extracting primitive
04:15:36 | DEBUG: Adding primitive without splitting. Indices: 10404 Vertices: 2754
04:15:36 | INFO: Primitives created: 1
04:15:36 | INFO: Extracting primitive
04:15:37 | DEBUG: Adding primitive without splitting. Indices: 18234 Vertices: 3628
04:15:37 | INFO: Primitives created: 1
04:15:37 | INFO: Extracting primitive
04:15:37 | INFO: Primitives created: 0
Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 356, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 33, in save
    json, buffer = __export(export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 42, in __export
    __add_root_objects(exporter, export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 57, in __add_root_objects
    scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 35, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 61, in __gather_animations
    animations += gltf2_blender_gather_animations.gather_animations(blender_object, export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 37, in gather_animations
    animation = __gather_animation(blender_action, blender_object, export_settings)
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 48, in __gather_animation
    if not __filter_animation(blender_action, blender_object, export_settings):
  File "C:\Users\Pedro\Desktop\blender-2.80.0-git.4d795cee4938-windows64\2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 72, in __filter_animation
    if blender_action.users == 0:
AttributeError: 'NoneType' object has no attribute 'users'

**Comment by UX3D-schmithuesen** [comment]
The bug mentioned here is fixed in #216. Sadly, the output doesn't look like you'd expect, but that's a different tale.
