### ISSUE TITLE
Blender 4.0.1 Fails to Load, NODE_OT_GLTF_SETTINGS

### ISSUE THREAD

**Issue by Shinmera** [KhronosGroup/glTF-Blender-IO#2066]
**Describe the bug**
I updated to 4.0.1 and imported my settings. Initially the glTF entries from the import/export menu were gone so I disabled and re-enabled the plugin. When re-enabling, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/usr/share/blender/4.0/scripts/addons/io_scene_gltf2/__init__.py", line 1661, in register
    blender_ui.register()
  File "/usr/share/blender/4.0/scripts/addons/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 520, in register
    bpy.utils.register_class(NODE_OT_GLTF_SETTINGS)
ValueError: register_class(...): already registered as a subclass 'NODE_OT_GLTF_SETTINGS'
```

**To Reproduce**
1. Update to 4.0.1
2. Import previous settings
3. Disable and re-enable the gltf add-on

**Version**
 - OS: Arch linux
 - Blender Version: 4.0.1

**Comment by julienduroure** [comment]
Hello,
This is not the first report about 4.0.1 on Arch
Seems you have to contact the maintainer of the package on Arch, something is wrong on Arch packaging side.
We can't reproduce by using the official Blender download
