### ISSUE TITLE
'NoneType' object has no attribute 'joints'

### ISSUE THREAD

**Issue by ShortVanco** [KhronosGroup/glTF-Blender-IO#2090]
I already saw this issue in #1738 issue and you seemed to say that it was fixed, but it appears again in version 4

`Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
2023-12-19 11:07:02,619 - ERROR - [runConvert:1719] - Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\python\python.py", line 1696, in runConvert
    bpy.ops.export_scene.gltf(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 613, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109`

**Comment by julienduroure** [comment]
Hello,
Please provided the .blend to be able to reproduce, as requested in template of the issue that you deleted.
I can not reproduce with the test file from #1738, so even if the traceback is the same, root cause is different.

**Comment by ShortVanco** [comment]
> 您好， 请按照您删除的问题模板中的要求提供 .blend，以便能够重现。 我无法使用 #1738 中的测试文件进行重现，因此即使回溯相同，根本原因也是不同的。



> 您好， 请按照您删除的问题模板中的要求提供 .blend，以便能够重现。 我无法使用 #1738 中的测试文件进行重现，因此即使回溯相同，根本原因也是不同的。

[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13711809/test.zip)

**Comment by ShortVanco** [comment]
> Hello, Please provided the .blend to be able to reproduce, as requested in template of the issue that you deleted. I can not reproduce with the test file from #1738, so even if the traceback is the same, root cause is different.
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13711812/test.zip)

**Comment by julienduroure** [comment]
Confirmed.
You have multiple objects, (of type meshes) that have no vertices.
This is the root cause of the issue.
Delete these objects, and you will be able to export.
Fix in progress to avoid crash in that case
