### ISSUE TITLE
Importer fails with some files containing vertex color data

### ISSUE THREAD

**Issue by ultrasuperpingu** [KhronosGroup/glTF-Blender-IO#212]
I don't know if this submit can be useful since I cannot provide the data file (sorry). I tried to reproduce with dummy data but I wasn't able to do it. I can provide the gltf json file but I tried it with a dummy all zero bin file and it imports without any problem. If I export (from UnityGLTF) removing an object (whatever which one), the import is ok. The file contains multiple instance of the same objects. I hope this can help anyway.

Here is the stacktrace:

Traceback (most recent call last):
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 467, in execute
    return self.import_gltf2(context)
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 485, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 32, in create
    BlenderScene.create(gltf, scene_idx)
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 57, in create
    BlenderNode.create(gltf, node_idx, None)  # None => No parent
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 138, in create
    BlenderNode.create(gltf, child_idx, node_idx)
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 70, in create
    BlenderMesh.set_mesh(gltf, gltf.data.meshes[pynode.mesh], mesh, obj)
  File "F:\blender-2.80.0-git.91a155833e59-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 173, in set_mesh
    vertex_color.data[loop_idx].color = vertex_color_data
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

location: <unknown location>:-1
[dummy.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2736384/dummy.zip)

**Comment by julienduroure** [comment]
@ultrasuperpingu Thanks for your report.
Are you able to share privately your glb/gltf file? In that case, you can provide me on private message (twitter, mail...) a link to file.

**Comment by ultrasuperpingu** [comment]
It would be my decision, I would have no problem to do it. Those data are not sensible at all in my opinion but it's not ours. I need the authorization of my client and I'm pretty sure the answer will be no. Sorry. I am still tring to reproduce the problem with dummy data. I'll let you no.

**Comment by ultrasuperpingu** [comment]
I was finally able to reproduce the problem.
I investigated a little and it seems that the importer try to read mesh from bin file multiple times when this mesh is instanciated multiple times in the scene. So, after the import (doesn't matter if imports failed or not), there is multiple Vertex Color channels on objects. In file gltf2_blender_mesh.py, I don't understand why vertex_color would be None (line 173) since it should be created line 159, but anyway, I guess this code (or at least part of it) should only be executed once by mesh data. Here is a cube base dataset reproducing the problem
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2736754/test.zip)

**Comment by julienduroure** [comment]
Thanks a lot for the test file, it will help a lot.
Will check it as soon as possible

**Comment by julienduroure** [comment]
Multiple problems here:
- On each instance, a vertex color was created. Blender has a limit of 10 different vertex color, so on the 11th instance, no vertex color was created ( and was None).

- Currently in importer, only COLOR_0 is managed. A new issue will be opened to manage multiple COLOR_X attributes
