### ISSUE TITLE
Error when trying to export anything in .glb, using recent versions from gitHub and Blender 4.0.2

### ISSUE THREAD

**Issue by kokotron** [KhronosGroup/glTF-Blender-IO#2161]
I'm trying to export anything (from a single cube to a more complex scene with armatures etc.) and I get the following error. I just updated to 4.2.5 to see if the issue was still there, I had it for some time but I can't remember when it started. I had last updated the plugin about a month ago. I'm using Blender 4.0.2. It has been the same error every time. I suspect I should recover the original version that shipped with 4.0.2, because of changes concerning normals in 4.1 which you're preparing for?

Python: Traceback (most recent call last):
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1167, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 94, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 52, in gather_node
    mesh = __gather_mesh(vnode, blender_object, export_settings)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 324, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 68, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 145, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 67, in gather_primitives
    blender_primitives, addional_materials_udim = __gather_cache_primitives(materials, blender_mesh, uuid_for_skined_data,
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 134, in __gather_cache_primitives
    blender_primitives, additional_materials_udim, shared_attributes = gltf2_blender_gather_primitives_extract.extract_primitives(
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 38, in extract_primitives
    primitive_creator.populate_dots_data()
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 360, in populate_dots_data
    attr['get'](attr)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 942, in getting_function
    self.__get_normal_attribute(attr)
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 1210, in __get_normal_attribute
    self.__get_normals()
  File "C:\E\PortablePrograms\Blender Launcher\stable\blender-4.0.2-stable\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 1167, in __get_normals
    self.blender_mesh.corner_normals.foreach_get('vector', self.normals)
TypeError: foreach_get(..) sequence length mismatch given 12, needed 0

**Comment by julienduroure** [comment]
Hello,

No bug here.
As you can see in addon header (here : https://github.com/KhronosGroup/glTF-Blender-IO/blob/e1cffe2169809206fe31049a787c73bfeab2959b/addons/io_scene_gltf2/__init__.py#L19), the minimal version compatible with current main branch is 4.1

You can not use old version of Blender with recent addon version, because of Blender API changes

Closing this ticket
