### ISSUE TITLE
Exporting with 'None' images throws errors and fails to export

### ISSUE THREAD

**Issue by kursad-k** [KhronosGroup/glTF-Blender-IO#2165]
**Describe the bug**
It seems like there is an issue with exporting glTF without images.

**To Reproduce**
Load the attached file
Export glTF
make sure images set to None

**Expected behavior**
It should export glTF without images.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/67970138/9cdefe1d-16e5-4d0a-b7b4-a2f7a50c8e10)

**.blend file/ .gltf (mandatory)**
[test_scene_a.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14622625/test_scene_a.zip)

**Version**
 - OS: Windows
 - Blender Version 2e6a8ae49c1c  build date: 2024-03-15

```

Traceback (most recent call last):

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\__init__.py", line 1175, in execute

    res = gltf2_blender_export.save(context, export_settings)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 38, in save

    json, buffer = __export(export_settings)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 56, in __export

    __gather_gltf(exporter, export_settings)

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 85, in __gather_gltf

    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)

                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 30, in gather_gltf2

    scenes.append(__gather_scene(blender_scene, export_settings))

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached

    result = func(*args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 84, in __gather_scene

    node = gltf2_blender_gather_nodes.gather_node(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 47, in gather_node

    children=__gather_children(vnode, export_settings),

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 94, in __gather_children

    node = gather_node(c, export_settings)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 41, in gather_node

    mesh = __gather_mesh(vnode, blender_object, export_settings)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 313, in __gather_mesh

    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached

    result = func(*args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 57, in gather_mesh

    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 134, in __gather_primitives

    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached

    result = func(*args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 56, in gather_primitives

    blender_primitives, addional_materials_udim = __gather_cache_primitives(materials, blender_mesh, uuid_for_skined_data,

                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached

    result = func(*args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 123, in __gather_cache_primitives

    blender_primitives, additional_materials_udim, shared_attributes = gltf2_blender_gather_primitives_extract.extract_primitives(

                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 29, in extract_primitives

    primitive_creator.manage_material_info() # UVMap & Vertex Color

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\blender\4.2\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 538, in manage_material_info

    tiles = [t.number for t in image.tiles]

                               ^^^^^^^^^^^

AttributeError: 'bool' object has no attribute 'tiles'




```

**Comment by julienduroure** [comment]
Confirmed. Fix in progress

**Comment by kursad-k** [comment]
Thanks for taking a look at it. Do the Blender Nightlies include the latest updates from this add-on? I want to test it but I want to make sure I am using the right versions.

**Comment by julienduroure** [comment]
Yes, it is, starting from Build of March 17th
