### ISSUE TITLE
Exporter crash with Collections and Lights

### ISSUE THREAD

**Issue by SolarLune** [KhronosGroup/glTF-Blender-IO#2189]
**Describe the bug**
When exporting a scene that contains a collection instance of an object and the exporter settings set to include Punctual Lights, the export process crashes with the following result:

```Python: Traceback (most recent call last):
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/__init__.py", line 1131, in execute
    return gltf2_blender_export.save(context, export_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 39, in save
    json, buffer = __export(export_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 56, in __export
    __gather_gltf(exporter, export_settings)
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 85, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 36, in wrapper_cached
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 84, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 49, in gather_node
    extensions=__gather_extensions(vnode, export_settings),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 188, in __gather_extensions
    if vnode.data.type in LIGHTS:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type'

```

This is observed using either the UI or the Python function to export GLTF scenes. This is observed in the Linux Flatpak version of Blender 4.1.0, as well as the standalone 4.1.1 release candidate as of 4/1/24. This is _not_ observed on the standalone Blender 4.0.3 release candidate from 12/18/23.

**To Reproduce**
1. Download the example blend file.
2. Export the result to a GLTF or GLB file.
3. See error.

In the packaged example, the pyramid object is in the same scene as the collection instanced object.

**Expected behavior**
The file should be exported without issues.

**.blend file/ .gltf (mandatory)**

[gltfExporterProblemExample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14828924/gltfExporterProblemExample.zip)

**Version**
- OS: Linux, Endeavour OS
- Blender Version: 4.1.0 (Date: 2024-03-25, Hash: 40a5e739e270)

EDIT: Updated wording.

**Comment by julienduroure** [comment]
Confirmed
