### ISSUE TITLE
glTF 2.0 export error when including punctual lights and full collection hierarchy

### ISSUE THREAD

**Issue by Torbernight** [KhronosGroup/glTF-Blender-IO#2204]
**Describe the bug**
When attempting to export my scene as glTF 2.0 including punctual lights and full collection hierarchy, it throws  "AttributeError: 'Collection' object has no attribute 'type'"

When disabling either of those two export settings, it exports correctly

**To Reproduce**
1. Create any scene, even the default general scene works
2. Select "File > Export > glTF 2.0 (.glb/.gltf)"
3. Select export settings "Include > Punctual Lights" and "Data > Scene Graph > Full Collection Hierarchy"
4. Export glTF 2.0

**Expected behavior**
It should export correctly as a glTF file

**.blend file**
[test.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15013257/test.blend.zip)

**Version**
 - OS: Arch Linux 
 - Blender Version: 4.1

**Additional context**
Full python traceback:
```
Python: Traceback (most recent call last):
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/__init__.py", line 1131, in execute
    return gltf2_blender_export.save(context, export_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 39, in save
    json, buffer = __export(export_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 56, in __export
    __gather_gltf(exporter, export_settings)
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 85, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 36, in wrapper_cached
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 84, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 48, in gather_node
    children=__gather_children(vnode, export_settings),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 95, in __gather_children
    node = gather_node(c, export_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 49, in gather_node
    extensions=__gather_extensions(vnode, export_settings),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 190, in __gather_extensions
    elif export_settings["gltf_lights"] and blender_object is not None and (blender_object.type == "LAMP" or blender_object.type == "LIGHT"):
                                                                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Collection' object has no attribute 'type'
```

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting.
This is already fixed in main branch (that will be 4.2)
