### ISSUE TITLE
Import: 'bpy_prop_collection[key]: key "" not found'

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#243]
```
Traceback (most recent call last):
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 468, in execute
    return self.import_gltf2(context)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 487, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 35, in create
    BlenderScene.create(gltf, scene_idx)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 97, in create
    bpy.data.objects[gltf.data.nodes[node_idx].blender_object].parent = obj_rotation
KeyError: 'bpy_prop_collection[key]: key "" not found'
```

[Test file](https://github.com/KhronosGroup/glTF-Blender-IO/files/2784544/b00A.zip)

Possibly caused by the mesh being in a different tree than the nodes used for skinning.

    mesh is here -> o       o   <- all the nodes used for skinning
                           / \     are over here
                          o   o
                             / \
                            o   o

**Comment by julienduroure** [comment]
Hello,
It seems that this is not the origin of the bug, but the cause seems to be that one of your root node is a joint/bone.

Should be fixed soon
