### ISSUE TITLE
Some recent blender2.8 commits broke the importer

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#266]
commit 7894d6c6f1982f58dc479f3f01dd79afb6f5c1a0 (HEAD -> master, origin/master, origin/HEAD)
Date:   Wed Jan 30 09:03:37 2019 +1100

6b465fdceb8d05c5836c55234f07fb7a658246e2 release/scripts/addons 

E.g. by import [cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2810114/cube.zip) :

```
Traceback (most recent call last):
  File "bin/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 468, in execute
    return self.import_gltf2(context)
  File "bin/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 487, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 33, in create
    BlenderScene.create(gltf, scene_idx)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 66, in create
    BlenderNode.create(gltf, node_idx, None)  # None => No parent
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py", line 50, in create
    mesh = BlenderMesh.create(gltf, pynode.mesh, node_idx, parent)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 44, in create
    verts, edges, faces = BlenderPrimitive.create(gltf, prim, verts, edges, faces)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_primitive.py", line 67, in create
    BlenderMaterial.create(gltf, pyprimitive.material, vertex_color)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py", line 79, in create
    BlenderPbr.create(gltf, pymaterial.pbr_metallic_roughness, mat.name, vertex_color)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_pbrMetallicRoughness.py", line 28, in create
    BlenderPbr.create_nodetree(gltf, pypbr, mat_name, vertex_color)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_pbrMetallicRoughness.py", line 39, in create_nodetree
    material.diffuse_color = pypbr.base_color_factor[:3]
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1
```

**Comment by julienduroure** [comment]
Fixed, thanks!
It's now merged with Blender code, should be available into build of tomorrow
