### ISSUE TITLE
Can't export animations on NLA tracks

### ISSUE THREAD

**Issue by tomo0613** [KhronosGroup/glTF-Blender-IO#347]
My problem is that i can't export stashed or pushed animations from NLA editor, only 1 animation is exported every time.

I'm getting the following messages on the console
"ERROR: Invalid count 0"
"WARNING: Skipping sampler {boneName}_{actionName}_translation, found missing or invalid data."
"WARNING: Skipped channel in action stand, missing sampler."

Tried to debug but couldn't managed it.
The trace that i followed:
    the log "Invalid count 0" comes from `create_accessor()`
    that is called from `generate_animations_parameter()` when dealing with translation_data
    there is part commented `# Sampler doesn't exist, lets create it`
    `keys = sorted(translation_data.keys())` keys are always empty[]

I've seen many issues about exporting multiple animations, however now it should work, based on other  GitHub issues.
So maybe my model has something to do with it, but the animations just work one-by-one, even if I import the model to Three.js

https://rawgit.com/tomo0613/2d-coa-test/master/index.html

**Comment by donmccurdy** [comment]
Transferring this to the new repository - the model now exports with multiple animations, but the skinning animation is incorrect.

**Comment by tomo0613** [comment]
Thanks for the update.

As i wanted to test, and replaced the exporter blender addon, i got the message below.
```
Traceback (most recent call last):
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 289, in execute
    from .blender.exp import gltf2_blender_export
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 22, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 18, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_nodes
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 24, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_mesh
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 19, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_primitives
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 24, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_materials
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 20, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_texture_info, gltf2_blender_export_keys
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 19, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_texture
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 22, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_image
  File "/home/tomo/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 19, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
I guess it only works under 2.8beta, but I failed to launch that as well "libmvec.so.1: cannot open shared object file"...
I think just wait for the stable releases.

**Comment by donmccurdy** [comment]
This model now exports correctly when *Always sample animations* is enabled.

Closing this issue, and tracking the dependence on that option in https://github.com/KhronosGroup/glTF-Blender-IO/issues/558.
