### ISSUE TITLE
duplicate linked causes AttributeError: 'NoneType' object has no attribute 'data' when using draco compression

### ISSUE THREAD

**Issue by leon** [KhronosGroup/glTF-Blender-IO#440]
**Describe the bug**
When using duplicate linked to reduce size of my gltf file I came across this bug.

If I export the gltf without the new draco compression everything works as expected.
But as soon as I enable draco, It fails with this stacktrace

```
09:55:29 | INFO: Starting glTF 2.0 export
09:55:29 | INFO: Extracting primitive: Cube
09:55:29 | DEBUG: Adding primitive without splitting. Indices: 36 Vertices: 24
09:55:29 | INFO: Primitives created: 1
Compressing mesh Cube
DRACO-COMPRESSOR: Compressing primitive:
DRACO-COMPRESSOR: Compression level [0-10]:   6
DRACO-COMPRESSOR: Position quantization bits: 14
DRACO-COMPRESSOR: Normal quantization bits:   10
DRACO-COMPRESSOR: Position quantization bits: 12
Compressing mesh Cube.001
Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 424, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 54, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 72, in __gather_gltf
    gltf2_io_draco_compression_extension.compress_scene_primitives(scenes, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_draco_compression_extension.py", line 114, in compress_scene_primitives
    __traverse_node(node, dll, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_draco_compression_extension.py", line 121, in __traverse_node
    __compress_primitive(primitive, dll, export_settings)
  File "/Applications/blender.app/Contents/Resources/2.80/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_draco_compression_extension.py", line 135, in __compress_primitive
    dll.addPositionAttribute(compressor, attributes['POSITION'].count, attributes['POSITION'].buffer_view.data)
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1
```

**To Reproduce**
1. Create new scene
2. select cube and press alt d to duplicate linked the cube
3. export to gltf and select draco compression.
4. see bug

**Expected behavior**
Export should work as normal

**Comment by UX3D-eckerlein** [comment]
Same issue here #445.
