### ISSUE TITLE
Index out of range when importing glTF

### ISSUE THREAD

**Issue by UX3D-becher** [KhronosGroup/glTF-Blender-IO#49]
There seems to be a bug in the importer, that results in the following error when importing [project_polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) and other glTF files.
```
Traceback (most recent call last):
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\__init__.py", line 522, in execute
    return self.import_gltf2(context)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\__init__.py", line 542, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 27, in create
    BlenderScene.create(gltf, scene_idx)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 49, in create
    BlenderNode.create(gltf, node_idx, None) # None => No parent
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 100, in create
    BlenderNode.create(gltf, child_idx, node_idx)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 65, in create
    BlenderMesh.set_mesh(gltf, gltf.data.meshes[pynode.mesh], mesh, obj)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 54, in set_mesh
    offset = BlenderPrimitive.set_normals(gltf, prim, mesh, offset)
  File "C:\Users\Moritz Becher\Developer\UX3D\glTF-Blender-IO\addons\io_scene_gltf2\blender\imp\gltf2_blender_primitive.py", line 80, in set_normals
    vert0 = mesh.vertices[calc_norm_vertices[0]].co
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by julienduroure** [comment]
Fixed in 5d3c15819a3b6aae6bcd23ad5fc8a16623228f2d
