### ISSUE TITLE
Importing material without pbrMetallicRoughness fails

### ISSUE THREAD

**Issue by ultrasuperpingu** [KhronosGroup/glTF-Blender-IO#64]
The importer should not assume that the pbrMetallicRoughness node is present in a material node.

To reproduce:
Just exports a tiny scene with materials and remove the pbrMetallicRoughness node from a material. Try then to reimport.

Here is the statcktrace:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\__init__.py", line 515, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\__init__.py", line 535, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 27, in create
    BlenderScene.create(gltf, scene_idx)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 49, in create
    BlenderNode.create(gltf, node_idx, None) # None => No parent
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 43, in create
    mesh = BlenderMesh.create(gltf, pynode.mesh, node_idx, parent)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 40, in create
    verts, edges, faces = BlenderPrimitive.create(gltf, prim, verts, edges, faces)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_primitive.py", line 62, in create
    BlenderMaterial.create(gltf, pyprimitive.material, vertex_color)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_material.py", line 41, in create
    BlenderPbr.create(gltf, pymaterial.pbr_metallic_roughness, mat.name, vertex_color)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_pbrMetallicRoughness.py", line 23, in create
    BlenderPbr.create_cycles(gltf, pypbr, mat_name, vertex_color)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_pbrMetallicRoughness.py", line 34, in create_cycles
    if pypbr.color_type == gltf.SIMPLE and not vertex_color:
AttributeError: 'NoneType' object has no attribute 'color_type'

**Comment by modulesio** [comment]
I'm still getting this one when loading Google Poly GLTF models:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 528, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 549, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 41, in create
    BlenderScene.create(gltf, scene_idx)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 79, in create
    BlenderNode.create(gltf, node_idx, None)  # None => No parent
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 169, in create
    BlenderNode.create(gltf, child_idx, node_idx)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 93, in create
    BlenderMesh.set_mesh(gltf, gltf.data.meshes[pynode.mesh], mesh, obj)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 86, in set_mesh
    BlenderPrimitive.set_UV_in_mat(gltf, prim, obj, vertex_color)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_primitive.py", line 189, in set_UV_in_mat
    and gltf.data.materials[pyprimitive.material].pbr_metallic_roughness.color_type in \
AttributeError: 'NoneType' object has no attribute 'color_type'
```

**Comment by julienduroure** [comment]
Hello @modulesio
Can you please provide a test .gltf or .glb file, in order to reproduce the error?
Thanks !

**Comment by julienduroure** [comment]
More than a month without any answer, closing this ticket.
