### ISSUE TITLE
Exporting with "JPEG image" option selected throws exception when textures are not packed

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#894]
When exporting to Gltf with option "JPEG format (.jpg)" selected, if textures are not packed into blend file it will throw an exception: 

```
Traceback (most recent call last):
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 483, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 53, in __export
    __gather_gltf(exporter, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 62, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 56, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, blender_scene, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 46, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 64, in __gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 337, in __gather_mesh
    export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 42, in gather_mesh
    primitives=__gather_primitives(blender_mesh, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 129, in __gather_primitives
    export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 64, in gather_primitives
    export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 56, in gather_material
    pbr_metallic_roughness=__gather_pbr_metallic_roughness(blender_material, orm_texture, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 221, in __gather_pbr_metallic_roughness
    export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 33, in gather_material_pbr_metallic_roughness
    base_color_texture=__gather_base_color_texture(blender_material, export_settings),
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py", line 107, in __gather_base_color_texture
    return gltf2_blender_gather_texture_info.gather_texture_info(inputs, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 37, in gather_texture_info
    index=__gather_index(blender_shader_sockets_or_texture_slots, export_settings),
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 97, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets_or_texture_slots, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 48, in gather_texture
    source=__gather_source(blender_shader_sockets_or_texture_slots, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 97, in __gather_source
    return gltf2_blender_gather_image.gather_image(blender_shader_sockets_or_texture_slots, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 48, in gather_image
    uri = __gather_uri(image_data, mime_type, name, export_settings)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 124, in __gather_uri
    data=image_data.encode(mime_type=mime_type),
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 115, in encode
    return self.__encode_happy()
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 121, in __encode_happy
    return self.__encode_from_image(self.blender_image())
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 292, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format)
  File "/home/ali/.config/blender/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 308, in _encode_temp_image
    tmp_image.save()
RuntimeError: Error: Image 'Material_59.003_baseColor.png.001' does not have any image data


location: <unknown location>:-1


```
Linux OS
Blender v2.81
Gltf Addon v1.2.6

A test blend file: https://github.com/KhronosGroup/glTF-Blender-IO/files/4116950/untitled.blend.zip (Make sure to unpack texture before exporting)

**Comment by julienduroure** [comment]
Hello,
The 1.2.6 version should not be "out of the box" be installed in 2.81 version, except if you install manually a newer version than the addon version packaged with Blender. Can you please confirm that you indeed install a newer version manually?

If this is the case, can you please test if you get the same result with 2.82 beta? (that you can download on builder.blender.org)

**Comment by Ali-RS** [comment]
>Can you please confirm that you indeed install a newer version manually?

Yes, I installed a newer version manually from master branch. 

>If this is the case, can you please test if you get the same result with 2.82 beta?

Yes, I get the same result.

**Comment by julienduroure** [comment]
@scurest can you please have a look?

**Comment by scurest** [comment]
I can't reproduce this. What I'm doing:

1. open the Blender file
2. pick _File > External Data > Unpack All Into Files > Write files to current directory (overwrite existing files_
3. check that the image is unpacked
4. export with the _Geometry > Images_ option set to "JPEG format (.jpg)", all other options the default

**Comment by Ali-RS** [comment]
Ah, sorry forgot to mention, you also need to **_disconnect_** texture from the "Alpha" socket of the shader: 

![Screenshot_2020-01-27_15-22-56](https://user-images.githubusercontent.com/5787647/73172736-f5f95480-4118-11ea-9dd7-7a57a3073c06.png)

**Comment by scurest** [comment]
Okay, can confirm now!

This is that frustrating problem where it's really hard to save a copy of an existing image again :/ I don't have _any_ clue why you can't save the `img.copy()` here. It does appear to work if you've called update on the copy, so this one-liner seems to fix it

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
index 4011d6b..75f47cc 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py
@@ -286,6 +286,7 @@ class ExportImage:
         tmp_image = None
         try:
             tmp_image = image.copy()
+            tmp_image.update()
             if image.is_dirty:
                 tmp_image.pixels = image.pixels[:]
 
````

Maybe I should try to get the `save_as` code from [julienduroure's comment](https://github.com/KhronosGroup/glTF-Blender-IO/pull/798#issuecomment-562686834) working though.

**Comment by scurest** [comment]
I think calling `.update()` here is a good thing to do anyway. It also appears to make this piece of bizarreness unnecessary

https://github.com/KhronosGroup/glTF-Blender-IO/blob/fdaeb0865d85c610dc3d1fd02c596db582d2cb5a/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py#L303-L305

**Comment by Ali-RS** [comment]
Thanks for the quick fix :)
