### ISSUE TITLE
Vertex group index error

### ISSUE THREAD

**Issue by timsun28** [KhronosGroup/glTF-Blender-IO#909]
**Describe the bug**
While trying to export a model from Blender I get the following error: IndexError: bpy_prop_collection[index]: index 16 out of range, size 15
vertex_group_name = blender_vertex_groups[vertex_group_index].name

I have previously succesfuly exported this model as a GLB file, but after messing around with removing certain bones from vertex groupes I get this error and can't export the model anymore. 

If this issue is not solvable without supplying my model, I will be able to send it in private to someone who would want to help me, but I would rather not put it on github. 

Thank you in advance!

**Version**
 - OS: Ubuntu 19.10
 - Blender Version 2.81.16

Full error log: 
Traceback (most recent call last):
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/__init__.py", line 420, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 54, in __export
    __gather_gltf(exporter, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 69, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 36, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 55, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, blender_scene, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 45, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 59, in __gather_node
    children=__gather_children(blender_object, blender_scene, export_settings),
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 125, in __gather_children
    node = gather_node(child_object, blender_scene, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 45, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 63, in __gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 297, in __gather_mesh
    export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 41, in gather_mesh
    primitives=__gather_primitives(blender_mesh, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 117, in __gather_primitives
    export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 50, in gather_primitives
    vertex_groups, modifiers, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 94, in __gather_cache_primitives
    None, blender_mesh, blender_object, vertex_groups, modifiers, export_settings)
  File "/snap/blender/34/2.81/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py", line 714, in extract_primitives
    vertex_group_name = blender_vertex_groups[vertex_group_index].name
IndexError: bpy_prop_collection[index]: index 16 out of range, size 15

location: <unknown location>:-1

**Comment by julienduroure** [comment]
Hello,
Can you please send me the model in private? This will not be possible to find the issue without it.
You can use email (contact AT julienduroure.com), or twitter DM if you prefer

**Comment by julienduroure** [comment]
For info: I received the model in private. 
This is quite a big model, so investigation will not be really easy

**Comment by scurest** [comment]
(Not sure if this is helpful, or even the same issue or not :/)

I can get a backtrace to the same line (but I don't think this is the same way you did it).

<details><p>

<summary>Instructions to trigger</summary>

1. Create a rigged mesh. I just imported RiggedSimple.
2. Select the mesh in Object mode and press `Alt+D` to create a linked duplicate. Move the duplicate out of the way.
3. Select the duplicate and add a new Vertex Group to it. Now the original has N vertex groups and the duplicate has N+1 vertex groups.
4. Go into Weight Paint mode on the duplicate, select the new Vertex Group, and paint some vert. That vert now has a `.groups[i].group` index that is out-of-bounds for the Vertex Group list on the original object (but in bounds for the duplicate).
5. Export.

</p></details>

Explanation:

This code assumes that `D.meshes['mymesh'].vertex.groups[i].group` is a valid index into `blender_vertex_groups`:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/28e0ccf3fc153d38c286e435467e5fba79bc9be1/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L733-L734

The `blender_vertex_groups` variable is initialized here:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/28e0ccf3fc153d38c286e435467e5fba79bc9be1/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L260

`vertex_group_index` does not have to be a valid index into this (sort of like how a `material_idx` [does not have to be a valid index into `blender_object.material_slots`](https://github.com/KhronosGroup/glTF-Blender-IO/blob/28e0ccf3fc153d38c286e435467e5fba79bc9be1/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py#L66)).

So maybe the extract code should `continue` when `vertex_group_index` is not in bounds?

**Comment by julienduroure** [comment]
Thanks for this analysis.
So, linked to #900 too (maybe not directly linked, but we have to have it in mind when searching a solution for these 2 tickets)

**Comment by timsun28** [comment]
Just want to give you guys an update, I went ahead and restarted my project with a fresh model and used the things I learned in Blender to continue working on the project. 
If there is anyone else who would like to look into it, you can contact me, and I hope this can help fix this bug.

Thanks guys!
