### ISSUE TITLE
Error exporting shapekeys on blender 2.82

### ISSUE THREAD

**Issue by janEntikan** [KhronosGroup/glTF-Blender-IO#930]
When exporting a model using a combination of shapekeys, a shapekey animation and textures and checking "apply modifiers" in the export menu, the following error is produced:

```
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/__init__.py", line 481, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 53, in __export
    __gather_gltf(exporter, export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 62, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 56, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, blender_scene, export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 46, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 64, in __gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 311, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 43, in gather_mesh
    weights=__gather_weights(blender_mesh, vertex_groups, modifiers, export_settings)
  File "/usr/share/blender/2.82/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 138, in __gather_weights
    if not export_settings[MORPH] or not blender_mesh.shape_keys:
ReferenceError: StructRNA of type Mesh has been removed
```

What is strange is that either by removing the textures or by unchecking "apply modifiers", or removing the shapekey animation it seems to work fine, but put them all together and it stops working. 

This started happening after updating blender. 

**To reproduce**
1. make a cube with some shapekeys
2. make a simple shapekey (or armature) animation
3. give the shape a material with a texture
4. export as gltf, making sure "apply modifiers" is checked

**Expected behavior**
To export without errors.

**.blend file**
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4226562/test.zip)

**Version**
 - OS: Arch Linux
 - Blender 2.82 (sub 7) 
        build date: 2020-02-14
        build time: 16:19:45
        build commit date: 2020-02-13
        build commit time: 11:37
 Installed with pacman, from the official arch linux repository.

**Comment by h7seiji** [comment]
I seem to be having the same problem, but I'm not using shapekeys or animation at all. What I am also using, among the things you cite, is apply modifiers, and turning it off it works fine.

**Comment by julienduroure** [comment]
I will investigate.
In anyway, using "Apply Modifiers" prevents exporting shapekeys, this is a Blender and Blender API limitation, as described in export options:

![image](https://user-images.githubusercontent.com/1696020/74873715-025f7e80-5360-11ea-9c33-b3316f8a3d09.png)


Not sure yet why error occurs or not depending on material. Will investigate, seems to be linked to a Blender or Blender API regression.

**Comment by julienduroure** [comment]
My bad, this is not a regression, this error also happen in 2.81.
Seems to have different behaviour depending on the file.

**Comment by janEntikan** [comment]
Shapekeys used to be exported when the Apply Modifier flag was true but there were no modifiers present to apply. This made automatic exporting less complicated. With this solution I would have to keep track of what model has shapekeys, and then unset the flag, myself.

**Comment by bunnybones1** [comment]
Just had the same issue but discovered one more potential cause.
Normals autosmooth has to be disabled or shape keys won't export.
